### ISSUE TITLE
Ability to call CNA in cell lines

### ISSUE THREAD

**Issue by alhafidzhamdan** [AntonioDeFalco/SCEVAN#1]
Hi there,
Congrats on the new tool to call CNAs using single cell RNA-seq. I wonder how does your tool handle datasets without embedded normal cells? For example, immortalised cell lines? 

Al

**Comment by AntonioDeFalco** [comment]
Hi,
When our tool does not find normal cells in the analysed sample, it assumes that it is a pure tumour sample, and then a synthetic baseline is used to infer the copy number profile. 

Thanks for your interest in our work. Regards.

**Comment by alhafidzhamdan** [comment]
Great- i'll be testing with my samples- Thanks a lot!
A
