### ISSUE TITLE
version error

### ISSUE THREAD

**Issue by xiangwei6963** [AntonioDeFalco/SCEVAN#10]
Hi there,
   When I run"install_github("AntonioDeFalco/SCEVAN")", it always returns version 4.1.1 (2021-08-10). So How could I update it to version4.1.2(2021-11-01)?
  Thank you for the help!

**Comment by AntonioDeFalco** [comment]
Hi,
Are you sure you're referring to the version of our package, because we don't have that version number. However, if install_github does not give you the latest version of the repository, try uninstalling the package _remove.packages("SCEVAN")_, restarting R and then reinstalling.
