### ISSUE TITLE
Question about beta_vega and normal/tumor calls

### ISSUE THREAD

**Issue by mloberg16** [AntonioDeFalco/SCEVAN#100]
Hello, thank you for making this excellent tool! I have been using it on some scRNA sequencing data. I think it is doing an excellent job at calling some of the tumor cells. However, I believe that some of the normal cells may be subclones of the tumor cells (they have some of the same CNAs as the tumor cells but are being called normal). (See image below. In particular, the tumor cell duplications in 5, 7, 9, 11, 12, and 20, as well as the deletion in 13 are all present in a subset of the "normal" cells.) 

I'm wondering what parameters would affect/change the stringency of the tumor/normal call. Specifically, would altering the beta_vega parameter affect whether these cells with similar CNAs as tumor cells are called as malignant by SCEVAN? If it will not, are there other parameters that may affect whether these cells are called as tumor cells?

Additionally, is it possible to contain info about the cell IDs of a subset of the normal cells? I can extract tumor/normal and tumor subclone data, but I am having trouble figuring out which of the normal cells are the ones where I see a similar CNA pattern to the tumor cells. 

Thanks so much, 
Matthew

![24-0123_Lu_ATC12heatmap](https://github.com/AntonioDeFalco/SCEVAN/assets/80286246/c15dec91-e0c9-4f9b-8ad8-998542a28e27)

**Comment by AntonioDeFalco** [comment]
Hi @mloberg16,
Yes it seems that SCEVAN missed in the tumor classification a group of cells that I do not know whether they represent a subpopulation or a group of "lower quality" cells with fewer counts.

You can try changing the beta, but I also think you can refine the classification with, for example, the UMAP and clustering plot of the count matrix and also with the plot of the copy number as shown in the README.

![Screenshot 2024-04-18 at 11 53 44](https://github.com/AntonioDeFalco/SCEVAN/assets/11536289/1d380bf2-acf0-44d6-827e-2f467b5b1015)
