### ISSUE TITLE
Error in x$tmp_NES: $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by cmills2** [AntonioDeFalco/SCEVAN#102]
Hi, 

Thank you for making this exciting tool. I am using it on a single cell RNA seq dataset that I processed using scanpy. I converted the count matrix to a dense matrix and exported it as genes (rows) x cells (columns) as a csv. 

I installed SCEVAN today and am using the most recent version of the tool. I am using R version 4.3.2. 

I have the following issue, however, when I run: 
`results <- pipelineCNA(count_mtx, SUBCLONES = TRUE, plotTree = TRUE)`

Error:
1] " raw data - genes: 21948 cells: 15609"
[1] "1) Filter: cells > 200 genes"
[1] "filtered out 15195 cells past filtering 414 cells"
[1] "2) Filter: genes > 10% of cells"
[1] "21948 genes past filtering"
[1] "3) Annotations gene coordinates"
Warning message in parallel::mclapply(1:ncol(geData), execMww, mc.cores = ncore):
“scheduled core 1 encountered error in user code, all values of the job will be affected”
Error in x$tmp_NES: $ operator is invalid for atomic vectors
Traceback:

1. pipelineCNA(count_mtx, SUBCLONES = TRUE, plotTree = TRUE)
2. preprocessingMtx(count_mtx, sample, par_cores = par_cores, findConfident = normalNotKnown, 
 .     AdditionalGeneSets = AdditionalGeneSets, SCEVANsignatures = SCEVANsignatures, 
 .     organism = organism)
3. getConfidentNormalCells(count_mtx, sample, par_cores = par_cores, 
 .     AdditionalGeneSets = AdditionalGeneSets, SCEVANsignatures = SCEVANsignatures, 
 .     organism = organism)
4. system.time(ssMwwGst(geData = mtx, geneSet = geneSet, ncore = par_cores, 
 .     minLenGeneSet = 5, filename = paste0("./output/", sample, 
 .         "_confidentNormal"), standardize = TRUE))
5. ssMwwGst(geData = mtx, geneSet = geneSet, ncore = par_cores, 
 .     minLenGeneSet = 5, filename = paste0("./output/", sample, 
 .         "_confidentNormal"), standardize = TRUE)
6. sapply(ans, function(x) x$tmp_NES)
7. lapply(X = X, FUN = FUN, ...)
8. FUN(X[[i]], ...)
Timing stopped at: 9.833 9.417 3.818

If you could help me troubleshoot this issue, that would be very much appreciated!

**Comment by AntonioDeFalco** [comment]
Hi @cmills2 ,
Thanks for the report I have not tested SCEVAN on the recent version of R yet, I will do it soon. But I think the problem might be related to your analyzed sample, it seems very strange to me that out of 15609 only 414 are left after filtering. Have you also tried with another sample or a sample from the vignettes?

Thanks. Regards

**Comment by AntonioDeFalco** [comment]
SCEVAN was tested on 4.3.2, this issue is probably due to a bad sample.
