### ISSUE TITLE
Max # confident normal cells when specifying norm_cell?

### ISSUE THREAD

**Issue by DGladish** [AntonioDeFalco/SCEVAN#103]
Hello!

I am specifying norm_cell using a vector containing ~3500 cell barcodes. Does SCEVAN use them all to do the downstream steps? Or is a subset taken? If so, how is that subset selected?

Thank you :)

**Comment by AntonioDeFalco** [comment]
Hi @DGladish,
Sorry for the late reply, yes, SCEVAN uses them all (instead of the 30 confident normal cells that it would find by default by not using the norm_cell parameter) to create a reference normal cell copy number profile. It then runs all subsequent speps as described in the paper.

Thanks. Regards.

**Comment by DGladish** [comment]
Hey! @AntonioDeFalco 

Thanks so much for the reply! Your answer leads me to a follow-up question. I have been saving the variable that contains the output of pipelineCNA() as a .rds file. In this file, I see essentially 3 types of my normal cells:
 1) Normal cells that are confidentNormal = Yes and class = NA
 2) Normal cells that are confidentNormal = Yes and class = filtered
 3) Normal cells that are confidentNormal = Yes and class = tumor or normal

I assume that the ones that are class = filtered are filtered out in the same way as the ones in the cancer dataset used as input (i.e. the QC steps stated in the paper), but what happens to the cells that are confidentNormal = yes and class = NA? Are the cells manually specified as confidentNormal cells subjected to an additional QC step?

Thanks :)

**Comment by kennyyeo13** [comment]
Hi, I also see the same issue - is this because of this below code in preprocessingMtx, where its  genes.raw < 100 but should be <200.?

if (sum(genes.raw < 100) > 1) {
    count_mtx <- count_mtx[, -which(genes.raw < 200)]
}
