### ISSUE TITLE
Error in dataframe *tmp* replacement has x data has y

### ISSUE THREAD

**Issue by sinanassiri** [AntonioDeFalco/SCEVAN#106]
Hi, thanks for this great package!

I am getting an error for a few samples out of a large cohort, where the algorithm exits with error messages like below:

Error in `[<-.data.frame`(`*tmp*`, r, 1, value = c("8 (p23.3-p23.1) ",  : 
  replacement has 2 rows, data has 1

or

Error in `[<-.data.frame`(`*tmp*`, r, 1, value = c("13 (q12.11-q12.12) ",  : 
  replacement has 2 rows, data has 1

Usually, [Error in dataframe *tmp* replacement has x data has y] is caused by NAs but I can't figure out if/why that is the case here. Of note, the output dir at the time of exit looks like this:

![Screenshot 2024-03-12 at 16 08 43](https://github.com/AntonioDeFalco/SCEVAN/assets/12547111/fc49592e-9952-48fd-ad70-71462e1fa41d)

Also, I'm running SCEVAN_1.0.1 with default parameters via the latest docker image. You can access an example raw_count_matrix.rds to reproduce the error here: https://drive.google.com/file/d/1MRt2UGfAxpXEGX9i6ves4wLpYcvFfPU-/view?usp=sharing

raw_counts_matrix <- readRDS("./raw_counts_matrix.rds")
res_pip <- pipelineCNA(raw_counts_matrix)

I'm aware of this previous ticket (https://github.com/AntonioDeFalco/SCEVAN/issues/73) but as I'm using the latest release the issue seems to persist.

Thanks,
Sina

**Comment by AntonioDeFalco** [comment]
Hi @sinanassiri,
Thanks for this detailed issue. I have updated the docker image at the last commit of SCEVAN, which also solved this issue.
You can pull the last version and retry.

`docker pull anthonyphis/r_scevan`

Regards
