### ISSUE TITLE
some clarifications

### ISSUE THREAD

**Issue by aleednn** [AntonioDeFalco/SCEVAN#107]
- How can I get the barcodes present in each subclone? (tsne_CNA graph)
- tsne_CNA graph is done only on tumor cells?
- 
Thank you!

**Comment by AntonioDeFalco** [comment]
Hi @aleednn,

> * How can I get the barcodes present in each subclone? (tsne_CNA graph)

The pipeline outputs a data.frame with this information as well, as shown in the vignette. 

results <- pipelineCNA
![Screenshot 2024-03-29 at 11 50 29](https://github.com/AntonioDeFalco/SCEVAN/assets/11536289/7deb8ff4-0902-4a40-9086-007ff184b8e0)

> * tsne_CNA graph is done only on tumor cells?

Yes, only on tumor cells.

Regards

**Comment by aleednn** [comment]
Thank you @AntonioDeFalco for your reply.

i used:
results <- pipelineCNA(count_mtx, norm_cell =  listNormCells, sample = "pt", par_cores = 25, SUBCLONES = TRUE, plotTree = TRUE)

but the value of confidential_normal in results is always "yes" for both tumor and non-tumor cells.

What could be the problem?

Regards.
