### ISSUE TITLE
Error in data.frame - arguments imply differing number of rows

### ISSUE THREAD

**Issue by augjensen** [AntonioDeFalco/SCEVAN#109]
Hi!

I'm running SCEVAN and it works nicely, except for some samples were I get this error:

![image](https://github.com/AntonioDeFalco/SCEVAN/assets/145105837/0414aebd-ae19-410c-b8d1-4d1e92ab7b69)

**What is it in my data that causes these errors?** Rerunning them, I get the exact same error with the same numbers. 

Also, similarly when running the multi-sample comparison:

`results <- SCEVAN::multiSampleComparisonClonalCN(listCountMtx, analysisName = donor_id, organism = "human" , par_cores = 20)
`
I get the following error:

![image](https://github.com/AntonioDeFalco/SCEVAN/assets/145105837/1d66a653-379a-4e17-a613-73e1345e5c62)

**What can be the reason for this error and how can it be prevented?**

Thanks!

**Comment by Yunuuuu** [comment]
the same problem

**Comment by AntonioDeFalco** [comment]
The problem should have been fixed in the last commit [f1394b3](https://github.com/AntonioDeFalco/SCEVAN/commit/f1394b38a31375b620b5fca775e00f969ce89b19), check by reinstalling SCEVAN.

Thanks. Regards.
