### ISSUE TITLE
[Error] mtx[!Dupl_GeneName, ] : (subscript) logical subscript too long

### ISSUE THREAD

**Issue by autumnfe** [AntonioDeFalco/SCEVAN#113]
When I ran 'intratumoral heterogeneity' tutorial, I got the error.

I just ran the following code after downloading count-matrix file.

SCEVAN::pipelineCNA(count_mtx, sample = "MGH106", par_cores = 20, SUBCLONES = TRUE, plotTree = TRUE)

But, return this error:
[1] " raw data - genes: 23686 cells: 200"
[1] "1) Filter: cells > 200 genes"
[1] "2) Filter: genes > 10% of cells"
[1] "12304 genes past filtering"
[1] "3) Annotations gene coordinates"
mtx[!Dupl_GeneName, ] : (subscript) logical subscript too long

How to resolve this issue?

**Comment by cartographerJ** [comment]
I think the preprocessing commit broke something... 

this worked for me:
install_github("AntonioDeFalco/SCEVAN@e1c443c48b221b4350a05e3442d9d85867345616")

**Comment by AntonioDeFalco** [comment]
Sorry, it has now been fixed in the last commit [92761f6](https://github.com/AntonioDeFalco/SCEVAN/commit/92761f664dde885b04b4257d6b5250ffe0a8247b)
