### ISSUE TITLE
How to deal with EnsDb.Hsapiens.v86?

### ISSUE THREAD

**Issue by autumnfe** [AntonioDeFalco/SCEVAN#114]
When I ran SCEVAN, I encountered error.

So, I looked into the code of annotateGens function().

In the begining of code, I cound see the followin code:

if(organism == "human"){
    edb <- EnsDB_Hsapiens_v86 #From EnsDb.Hsapiens.v86
  }else{
    edb <- EnsDb_Mmusculus_v79 #From EnsDb.Hsapiens.v86
  }

Even if I load EnsDb.Hsapiens.v86 library, I couldn't see  'EnsDB_Hsapiens_v86' object. How to deal with this issue?

Also, when I see the code of preprocessMtx function(), I could see the following code:

if(organism == "human"){
    totChr <- 22
    cellcycle <- reactome_cellcycle #From EnsDb.Hsapiens.v86
  }else{
    totChr <- 19
    cellcycle <- reactome_cellcycle_Mmusculus #From EnsDb.Hsapiens.v86
  }

But, I couldn't find 'reactome_cellcycle' object at all.
How to resolve this issue?

**Comment by AntonioDeFalco** [comment]
They are objects stored within the R package, which you can find in the [sysdata.rda](https://github.com/AntonioDeFalco/SCEVAN/blob/main/R/sysdata.rda) of the R folder.
