### ISSUE TITLE
Running samples together versus one by one

### ISSUE THREAD

**Issue by kar6425** [AntonioDeFalco/SCEVAN#116]
I want to use SCEVAN solely for the purpose of classifying malignant versus normal cells in single cell data. I have several samples from the same scRNA-seq experiment but running all of them through SCEVAN together requires more memory than my computer has. Was wondering if there would be a difference in the accuracy of classification if I ran each sample by itself? For reference, each sample is 10,000-20,000 cells, and there are six samples that make up a total of ~90,000 cells.

**Comment by AntonioDeFalco** [comment]
Hi @kar6425,
the suggestion is to analyze each sample at a time for more accurate results, only if you have several samples from the same patient could you analyze them together. The reasoning is like CNV analysis from bulk with the matched normal, versus an analysis with a Panel of Normal (PoN) created from multiple healthy tissue samples.
