### ISSUE TITLE
Error: address 0x210c0, cause 'memory not mapped'

### ISSUE THREAD

**Issue by ywzhang071394** [AntonioDeFalco/SCEVAN#120]
Hi,
Thank you for this helpful tool.
However, I encountered a fatal error as below:

 *** caught segfault ***
address 0x210c0, cause 'memory not mapped'

Traceback:
 1: dyn.load(file, DLLpath = DLLpath, ...)
 2: library.dynam(lib, package, package.lib)
 3: loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]])
 4: asNamespace(ns)
 5: namespaceImportFrom(ns, loadNamespace(j <- i[[1L]], c(lib.loc,     .libPaths()), versionCheck = vI[[j]]), i[[2L]], from = package)
 6: loadNamespace(package, ...)
 7: doTryCatch(return(expr), name, parentenv, handler)
 8: tryCatchOne(expr, names, parentenv, handlers[[1L]])
 9: tryCatchList(expr, classes, parentenv, handlers)
10: tryCatch(loadNamespace(package, ...), error = function(e) e)
11: requireNamespace("ragg", quietly = TRUE)
12: plot_dev(device, filename, dpi = dpi)
13: ggplot2::ggsave(paste("./output/", samp, "OncoHeat.png", sep = ""),     device = "png", plotHeatmapOncoHeat$gtable, width = w, height = h,     dpi = 300)
14: plotOncoHeat(oncoHeat, nSub, samp, annotdf, mycolors, organism)
15: plotOncoHeatSubclones(oncoHeat, res_subclones$n_subclones, sample,     perc_cells_subclones, organism)
16: subcloneAnalysisPipeline(res_proc$count_mtx, res_class, res_proc,     mtx_vega, sample, par_cores, classDf, beta_vega, plotTree,     organism)
17: SCEVAN::pipelineCNA(cntmx, sample = "HT522", par_cores = 5, SUBCLONES = TRUE,     plotTree = TRUE, norm_cell = refvec)

Could you help check what happened? Thank you so much!

**Comment by ywzhang071394** [comment]
Solved.

**Comment by wudustan** [comment]
Can you explain how you solved it?
