### ISSUE TITLE
class "filtered" of cells

### ISSUE THREAD

**Issue by Ilarius** [AntonioDeFalco/SCEVAN#121]
Hello,
when looking at my results I found that a consistent set of cells receive a "filtered" label instead of normal/tumor.
Why is that?
In the paper it says that cells with less than 200 genes get filtered out but I already excluded cells with less than 500 genes.
However I do see that these cells have worse statistics.
What are the criteria to filter these cells out?

> summary(seu$nFeature_RNA[which(seu$SCEVAN=="filtered")])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  500.0   552.0   627.0   697.3   758.0  3933.0 
> summary(seu$nCount_RNA[which(seu$SCEVAN=="filtered")])
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  556.0   715.0   838.0   990.2  1075.0 10535.0 
  
  
![Screenshot 2024-08-29 at 17 20 07](https://github.com/user-attachments/assets/ba902812-cf57-430d-ae22-ad242a5b8ee3)

**Comment by AntonioDeFalco** [comment]
Hello @Ilarius,
As you can see in the public code during the pre-processing phase ([code](https://github.com/AntonioDeFalco/SCEVAN/blob/main/R/preProcessing.R#L152)), in addition to cells filtered by gene number, other cells are filtered out if they do not have at least 5 genes expressed on each chromosome (a necessary QC condition for copy number analysis).  

Regards.
