### ISSUE TITLE
Genes NOT in order of chromosomal location, how big an issue?

### ISSUE THREAD

**Issue by DGladish** [AntonioDeFalco/SCEVAN#122]
Hello!

I have been running SCEVAN on datasets that were produced by merging dataset associated with individual samples. The row names containing the gene symbols are initially ordered by chromosomal location, but I did not see that after using the merge() function on the individual dataset to create the combined datasets that I run SCEVAN on, the rows get put into alphabetical order based on the rownames (row 1 becomes A1BG, row 2=A1BG-AS1, row3=A1CF, etc.).

Is there any chance that SCEVAN has a step automatically correct this? It did accept the input and the algorithm ran to completion on all datasets structured like this.

**Comment by AntonioDeFalco** [comment]
Hello @DGladish,
Yes gene sorting is one of the steps in the pre-processing phase of SCEVAN.  

Regards
