### ISSUE TITLE
Correlation number of genes/counts

### ISSUE THREAD

**Issue by Ilarius** [AntonioDeFalco/SCEVAN#123]
I noticed a correlation between counts and tumor/healthy prediction.
(I am using all non-epithelial cells as reference).
Any tips on how to avoid this?

![Screenshot 2024-09-18 at 12 26 46](https://github.com/user-attachments/assets/fb26daf8-96ec-4c32-afe5-a70bae82de2b)

**Comment by AntonioDeFalco** [comment]
Hello @Ilarius,
Could you explain why you consider this correlation to be an issue? It’s well established in the literature that cancer cells express a large number of genes due to various factors, isn’t it?

Regards.
