### ISSUE TITLE
values from CNA matrix

### ISSUE THREAD

**Issue by abyssum** [AntonioDeFalco/SCEVAN#14]
Hello and thank you for this invaluable tool!

I have been trying to understand the CNA values reported as output from SCEVAN and I do have some trouble figuring out if I should use some threshold in order to call significant gains/losses. 

Could you please elaborate on how exactly the calculation of the CNA values works and if there is a need to use some specific cutoff?

Thank you

**Comment by AntonioDeFalco** [comment]
In the output segmentation file you can use Mean and the significance of loss and gain (L.pv/G.pv) for the call. I suggest for example to use as threshold to call Gain **Mean >= 0.10 and G.pv <= 0.05** and vice versa for Loss.

We will try to automate this call step in the next update. Thank you for your interest in our tool.

**Comment by abyssum** [comment]
Thank you for your prompt reply @AntonioDeFalco
