### ISSUE TITLE
Error in process

### ISSUE THREAD

**Issue by BertramLoong** [AntonioDeFalco/SCEVAN#16]
Hello, this algorithm is the most convenient one i've used.
But there was a problem in my results,  i don't know how to solve.

I input the pbmc dataset(after Seurat used and transfered to counts), but there was a error and the object 'results' not find:
<img width="447" alt="image" src="https://user-images.githubusercontent.com/81547213/170619526-737141e3-c0f7-4393-b1be-a2281fff788e.png">
<img width="648" alt="image" src="https://user-images.githubusercontent.com/81547213/170619366-2119a54e-0019-4bbb-b47e-ef21c5cfafd6.png">

**Comment by BertramLoong** [comment]
And piplelineCNA is a good function, but if there are some arguments or funtions  that i can  use  to output only judge whether tumor or normal by inputing only counts, because this maybe can speed up my using? Thanks a lot.

**Comment by AntonioDeFalco** [comment]
I will shortly check the problem you got on the pbmc dataset and correct it. If you are only interested in normal/tumour classification, you can use pipelineCNA with parameter SUBCLONES = FALSE.

Thanks for appreciating our tool.

**Comment by BertramLoong** [comment]
Thanks a lot, I look forward to your kind advice.

**Comment by BertramLoong** [comment]
And I  find if I use pipelineCNA with parameter SUBCLONES = FALSE in another testing dataset, there is a problem.
<img width="522" alt="image" src="https://user-images.githubusercontent.com/81547213/171001110-5d1d3b65-3912-404f-97b5-51117a2ff6b8.png">
<img width="970" alt="image" src="https://user-images.githubusercontent.com/81547213/171001154-a595d3be-eefe-44bf-bb9f-c8cb916b0b0c.png">
But if I use SUBCLONES = TRUE, this tool can run successfully.

**Comment by AntonioDeFalco** [comment]
I am sorry in one of the last commits I had mistakenly left an internal path. I have corrected the error in the last commit ([684363d](https://github.com/AntonioDeFalco/SCEVAN/commit/684363db5fcb1fe19591f9513ba7626e4bb590ee)). Let me know if that is all now. Reinstall SCEVAN and try again I believe this will also correct the previous error on pbmc dataset.

Thanks, regards.

**Comment by BertramLoong** [comment]
Great!!! 
I can run successfully, thanks a lot ~
