### ISSUE TITLE
Not getting clone tree

### ISSUE THREAD

**Issue by wbf520qcp** [AntonioDeFalco/SCEVAN#18]
Hi,
Thanks for developing this fantastic tool. I got a couple of problems when running my data.
(1) I first ran it on a small dataset (single patients with about 7000 cells). It worked all fine but only I didn't get the figure for clone tree. I tried a few different samples, but all missing that figure.

(2) When I ran it a large merged dataset (>50,000 cells). It raised the error "segfault"
<img width="1055" alt="Screen Shot 2022-05-31 at 4 09 19 PM" src="https://user-images.githubusercontent.com/56213252/171285193-efe8a52c-bb24-485c-9274-6a5431549401.png">

Any suggestions on that?
Thank you!

**Comment by AntonioDeFalco** [comment]
Thanks for appreciating our tool. (1) To obtain the clonal tree, set in the pipelineCNA function the attribute plotTree = FALSE. (2) It is probably a memory allocation error during the segmentation algorithm due to the large number of cells. I will try to solve this problem. In any case, in the meantime I recommend, particularly if they are different patients, running the pipeline for each individual sample and downstream aggregate and analyse the inferred copy number profiles. 

Regards.

**Comment by wbf520qcp** [comment]
Hi Just follow up on this. I got the exactly the same clonal tree as in tutorial. But in my case sub clones gather together and I see multiple gray circles. I'm wondering why is this. I expect to see subclones in a hierarchical way so I can tell which are in the early stage and which are late.

Thanks much,
Bofei

**Comment by AntonioDeFalco** [comment]
Thanks for the feedback. I changed some settings for the clone tree plot in the last commit [8a87431](https://github.com/AntonioDeFalco/SCEVAN/commit/8a874315d50c5ee7728954defd0893a5d34c2e0a) to get a better display. Reinstall SCEVAN with the latest commit and let me know if the display is now OK.

Sorry for the delay. Regards.

**Comment by wbf520qcp** [comment]
No worries. Thanks for making changes. I reinstalled SCEVAN and reran the same data, but got errors that stopped the running
Error in 1:totChr : NA/NaN argument
Calls: <Anonymous> ... subcloneAnalysisPipeline -> plotCNAline -> heatmap.3 -> unlist -> lapply
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted

Could you advise what the problem is?
Thanks

**Comment by AntonioDeFalco** [comment]
Sorry, try reinstalling now I have fixed the problem [f636cdb](https://github.com/AntonioDeFalco/SCEVAN/commit/f636cdbf85014fdb02c9a50b5b105a1207b82ef6).

Regards.

**Comment by wbf520qcp** [comment]
It worked, thank you very much. One more question about the interpret ion of this figure. According to the manuscript, the length of those branch represent the distance to the node, right? But in this tree, there are 3 gray circles, I wonder what are those gray circles representing and what is the x-axis indicate? 
![PT16ACloneTree](https://user-images.githubusercontent.com/56213252/172284899-3bea799b-8ae6-44ea-8df1-6f6792036b95.png)

**Comment by wbf520qcp** [comment]
![PT10ACloneTree](https://user-images.githubusercontent.com/56213252/172296356-d82ad54e-91a3-4fc4-bff7-eaf4b78acc7a.png)
In this plot, part of the sub clone label are masked.

**Comment by wbf520qcp** [comment]
Hi,
Just wanna check if this has been fixed? Some labels are not fully shown. Thanks

**Comment by AntonioDeFalco** [comment]
I tried to fix the problem in the last commit by adding extra space on the x-axis. 

Reinstall SCEVAN and let me know if everything is OK now. Thanks sorry for the delay.

**Comment by wbf520qcp** [comment]
I reinstalled it but still get the same as above. Also for some sample, I didn't get clone tree, OncoHeat etc. I wonder what the problem is. Thanks

**Comment by yh154** [comment]
Hi,

Is it possible to include sessionInfo() at the end of the tutorials given I've got conflicted package version errors as followings:

"Phylogenic tree cannot be plotted (ggtree requires dplyr version 1.0.5)"

I then installed dplyr 1.0.5, but got a different error:

Error: package or namespace load failed for ‘tidytree’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘dplyr’ 1.0.5 is already loaded, but >= 1.0.10 is required

Thanks!
yh

**Comment by yh154** [comment]
Hi, 

I still have trouble to get Phylogenic tree by following the first tutorial, "Intratumoral heterogeneity in Glioblastoma". I would appreciate if you could provide some insight. 

results <- SCEVAN::pipelineCNA(count_mtx, sample = "MGH106", par_cores = 20, SUBCLONES = TRUE, plotTree = TRUE)
.
[1] "Phylogenic tree cannot be plotted (ggtree requires dplyr version 1.0.5)"
[1] "time subclones:  2.16260516643524"
There were 50 or more warnings (use warnings() to see the first 50)

But, I have dplyr 1.1.0 installed: 

> packageVersion("dplyr")
[1] ‘1.1.0’

**Comment by AntonioDeFalco** [comment]
Hi @yh154 ,
I'm working on creating a docker image with an installation of SCEVAN, so that you can run it without having version problems. I will update you soon.

**Comment by AntonioDeFalco** [comment]
In the meantime try reinstalling SCEVAN (having installed dplyr 1.1.0 and updated ggtree) now after the last commit ([15fcce1](https://github.com/AntonioDeFalco/SCEVAN/commit/15fcce19b5dd7c265b5cd9f6bf9fa4631a22defc)) it should work correctly to create the Phylogenic tree.

**Comment by AntonioDeFalco** [comment]
@yh154  You can also try using the docker image : https://hub.docker.com/r/anthonyphis/r_scevan

**Comment by yh154** [comment]
> In the meantime try reinstalling SCEVAN (having installed dplyr 1.1.0 and updated ggtree) now after the last commit ([15fcce1](https://github.com/AntonioDeFalco/SCEVAN/commit/15fcce19b5dd7c265b5cd9f6bf9fa4631a22defc)) it should work correctly to create the Phylogenic tree.

Great! Works now!
