### ISSUE TITLE
Error with Seurat Input

### ISSUE THREAD

**Issue by tjbencomo** [AntonioDeFalco/SCEVAN#2]
Hi,

I'm encountering an error when using the counts matrix from a Seurat object as input to `pipelineCNA`. 

The following code crashes
```
results <- pipelineCNA(count_mtx = cells@assays$RNA@counts, sample = "test2", par_cores = 3, SUBCLONES = TRUE)
```
with the error
```
Error in t.default(newmtx) : argument is not a matrix
```
The crash happens after it has finished printing the `$test2_clone` clonal alterations. Looking at the source
code I think the next step if it didn't crash would be drawing the T-SNE plot and that the error originates from `plotHeatmap.R`. 

I think the error has something to do with the type of input matrix. Your vignette uses a matrix of class `"matrix" "array"`
while the Seurat matrix is class `"dgCMatrix"`. Converting the `cells@assays$RNA@counts` matrix to a non-sparse
matrix with `as.matrix(cells@assays$RNA@counts)` and using that as input seems to resolve the bug and allows SCEVAN to finish.

Assuming my hunch is correct and the type of input matrix is to blame, it would be nice to have support for Seurat sparse matrix input, although I'm not sure if this makes sense or is technically feasible. Even if not feasible, it would help to clarify in the documentation the type of input matrices allowed to avoid future user confusion.

**Comment by AntonioDeFalco** [comment]
Thank you for reporting the problem. I fixed the bug in the last commit [acd18c6](https://github.com/AntonioDeFalco/SCEVAN/commit/acd18c680b4fd9eb404339c5baef7f8cb5d75951), you should now be able to use sparse matrices without any problem.

Thanks for your interest. Regards
