### ISSUE TITLE
Identify cells & memory Issues

### ISSUE THREAD

**Issue by Romeo1-1** [AntonioDeFalco/SCEVAN#21]
Hello,

Thank you for this wonderful package, it's very easy to use ! I have 2 questions:

1) I'm comparing 10 samples from 5 patients, pre and post treatment. That's the code I'm running, where I mix both pre and post samples for each patient.

```
pre <- CreateSeuratObject(counts = pre_data, project = "pre", min.cells = 3, min.features = 200)
post <- CreateSeuratObject(counts = post_data, project = "post", min.cells = 3, min.features = 200)

pre_post <- merge(post, y = pre, add.cell.ids = c("post", "pre"), project = 'all')

pre_post$sample <- rownames(pre_post@meta.data)
pre_post@meta.data <- separate(pre_post@meta.data, col = 'sample', 
                                 into = c("Time", 'Barcode'), 
                                 sep = '_')

pre_post_matrix = GetAssayData(object = pre_post, slot = "counts")
pre_post_matrix = as.matrix(pre_post)

results <- SCEVAN::pipelineCNA(pre_post_matrix , sample = "P1", par_cores = 20, SUBCLONES = TRUE, plotTree = TRUE)
```

How could I know in the results which cells are "pre" and which are "post" ? Would it be possible at least to know the proportion of pre/post cells in each cluster ? I'm interested in the lineage of those cells.

2) I encountered memory issues (R crashing) when running the pipeline with 1 patient (= 2 samples mixed together) and most importantly when running the `multiSampleComparisonClonalCN` with the 10 samples. I'm running the analyses on a cluster with 32 cores and 128Gb. Do you have any idea how I would be able to run the analyses while using less memories ?

Thank you a lot in advance and thanks again

**Comment by AntonioDeFalco** [comment]
Hi @Romeo1-1 ,
regarding the analysis you want to carry out, if in the name of the cell you have added its belonging to "pre" or "post", you can easily obtain the information you want from the data frame in the output of SCEVAN, in which is contained for each cell the information about the subclones to which it belongs. In future updates, we plan to automate analyses such as yours of temporal samples.

Regarding the memory problem, could you tell me the size of the analysed matrices? In the last commit I modified the way of loading the matrix which should reduce the memory needed and avoid some problems in case of very large matrices. So you can try uninstalling and reinstalling SCEVAN and see if the problem still occurs. Please let me know.

Regards. Thanks for your interest.
