### ISSUE TITLE
Error during subclone identification

### ISSUE THREAD

**Issue by mmkhan19** [AntonioDeFalco/SCEVAN#23]
Hi, 

Thanks for developing this tool! I ran into an issue for one of my mouse samples with ~5K cells and this happens after the subclone identification step. Could you help me understand why this is happening or how it could be avoided? Thanks!

```
[1] "found 7 subclones"
percentage_cells_subsclone_1 percentage_cells_subsclone_2 
                  0.25609756                   0.15815549 
percentage_cells_subsclone_3 percentage_cells_subsclone_4 
                  0.19855183                   0.07583841 
percentage_cells_subsclone_5 percentage_cells_subsclone_6 
                  0.21303354                   0.06364329 
percentage_cells_subsclone_7 
                  0.03467988 
[1] "Segmentation of subclone :  1"
[1] "Segmentation of subclone :  2"
[1] "Segmentation of subclone :  3"
[1] "Segmentation of subclone :  4"
[1] "Segmentation of subclone :  5"
[1] "Segmentation of subclone :  6"
[1] "Segmentation of subclone :  7"
Error in sampleAlter[[sub2]] : subscript out of bounds
Calls: <Anonymous> -> subcloneAnalysisPipeline -> diffSubclones
Execution halted
```

**Comment by AntonioDeFalco** [comment]
Hi @mmkhan19,
I believe that in the latest commit [7b2f9cd](https://github.com/AntonioDeFalco/SCEVAN/commit/7b2f9cd0c5d2424c106bf77e00fa73b070a7d225) this problem should be solved. Reinstall SCEVAN and let me know if it works fine now. 

Thanks for your interest. Regards.

**Comment by mmkhan19** [comment]
Hi Antonio,

Thanks so much for fixing this issue I was able to run one of my samples successfully. Now I am getting this error again just for one sample (not the one mentioned previously). I ran it with 8, 16 and 24 cores on a cluster and don't know how to proceed with this. Any help would be appreciated. Thanks!
```
[1] "found 6 subclones"
percentage_cells_subsclone_1 percentage_cells_subsclone_2 
                  0.16568396                   0.16391509 
percentage_cells_subsclone_3 percentage_cells_subsclone_5 
                  0.28596698                   0.20872642 
percentage_cells_subsclone_6 percentage_cells_subsclone_7 
                  0.15035377                   0.02535377 
[1] "Segmentation of subclone :  1"
[1] "Segmentation of subclone :  2"
[1] "Segmentation of subclone :  3"
[1] "Segmentation of subclone :  4"

 *** caught segfault ***
address 0x13d470b00, cause 'memory not mapped'

Traceback:
 1: vegaMC_R(mtx = mtx, output_file_name = paste("./output/", sample,     "vega_output"), beta = beta_vega)
 2: getBreaksVegaMC(mtx_vega, CNAmat[, 3], paste0(samp, "_subclone",     i), beta_vega = 0.5)
 3: subclonesTumorCells(res_class$tum_cells, res_class$CNAmat, sample,     par_cores, beta_vega, res_proc, NULL, mtx_vega, organism = organism)
 4: subcloneAnalysisPipeline(count_mtx, res_class, res_proc, mtx_vega,     sample, par_cores, classDf, beta_vega, plotTree, organism)
 5: SCEVAN::pipelineCNA(count_mtx = count_mtx, sample = "KM_BM_0319_7",     ClonalCN = T, plotTree = T, organism = "mouse")
An irrecoverable exception occurred. R is aborting now ...
/var/spool/sge/scc-wc4/job_scripts/6487294: line 32: 12150 Segmentation fault
```

**Comment by AntonioDeFalco** [comment]
Does this sample have a higher number of cells/gens? It is a memory error that has never occurred to me, probably reducing the number of cores could solve the problem.

Let me know. Regards

**Comment by mmkhan19** [comment]
Hi Antonio,

Thanks for the reply. This sample has 28K genes and 2.6K cells. My other samples also have similar dimensions and the pipelineCNA had run successfully. I have reduced the `par_cores` from 20(default) to 8 and 4 but I still run into this issue. Maybe something related to a subclone having NULL entries and the code is trying to access the data? 

Thanks,
Muzamil

**Comment by AntonioDeFalco** [comment]
Sorry, I think I understood the problem and may have solved it with my last commit. Try reinstalling SCEVAN and let me know if it's OK now. 

Thanks. Regards.

**Comment by mmkhan19** [comment]
Great! It worked. Thanks so much. Should I rerun my previous samples which were run on the previous code? 

--Muzamil

**Comment by AntonioDeFalco** [comment]
Great, no it is not necessary. 

Regards.

**Comment by xxbb23** [comment]
Hi！
I encountered this problem again, I ran it with 20 and 15 cores and It reported an error . This sample has 2.5K genes and 1.9K cells.what should I do?
please help me！

[1] "found 10 subclones"
 percentage_cells_subsclone_1  percentage_cells_subsclone_3 
                   0.07821342                    0.22352466 
 percentage_cells_subsclone_4  percentage_cells_subsclone_6 
                   0.09559418                    0.02405012 
 percentage_cells_subsclone_7  percentage_cells_subsclone_8 
                   0.19765562                    0.05315279 
 percentage_cells_subsclone_9 percentage_cells_subsclone_10 
                   0.11034762                    0.12267583 
percentage_cells_subsclone_11 percentage_cells_subsclone_12 
                   0.05113177                    0.04365400 
[1] "Segmentation of subclone :  1"
[1] "Segmentation of subclone :  2"

 *** caught segfault ***
address 0x5641d7087cf0, cause 'memory not mapped'

Traceback:
 1: vegaMC_R(mtx = mtx, output_file_name = paste("./output/", sample,     "vega_output"), beta = beta_vega)
 2: getBreaksVegaMC(mtx_vega, CNAmat[, 3], paste0(samp, "_subclone",     i), beta_vega = 0.5)
 3: subclonesTumorCells(res_class$tum_cells, res_class$CNAmat, sample,     par_cores, beta_vega, res_proc, NULL, mtx_vega, organism = organism)
 4: subcloneAnalysisPipeline(res_proc$count_mtx, res_class, res_proc,     mtx_vega, sample, par_cores, classDf, beta_vega, plotTree,     organism)
 5: pipelineCNA(count_mtx, sample = "all_Epi3", par_cores = 15, norm_cell = norm_cell_list,     SUBCLONES = TRUE, beta_vega = 0.5, ClonalCN = TRUE, plotTree = TRUE,     organism = "human")

**Comment by RafaellaFerraz** [comment]
Hi,

Thanks for developing this tool! I encountered this problem again. Could you help me understand why this is happening or how it could be avoided? Thanks!

[...]
[1] "8) Smoothing data"
[1] "9) Segmentation (VegaMC)"
[1] "10) Adjust baseline"
[1] "11) plot heatmap"
[1] "found 4370 tumor cells"
[1] "time classify tumor cells:  6.43166528145472"
Error in sampleAlter[[sub2]] : subscript out of bounds
Calls: source ... withVisible -> eval -> eval -> <Anonymous> -> diffSubclones
