### ISSUE TITLE
Error and questions

### ISSUE THREAD

**Issue by StevenTur** [AntonioDeFalco/SCEVAN#24]
Hi thank you for your help about my previous problem.

I have several questions about the program.

Whats is the maximum numbers of cells ?

In a test i have nooticed that some cells are called "tumors" and "filtered". What is the meaning of filtered exactly ? is it mean diploid or normal cells ?

I have change my computer and i tried the program again on 21000 cells and i encounter this error : 

![image](https://user-images.githubusercontent.com/106545864/186324095-ed4ac97e-e20a-4441-a9a1-78e226eaae65.png)

Can you help me on that ?

Thanks again for your help,

Steven

**Comment by AntonioDeFalco** [comment]
Hi @StevenTur,
Filtered cells are those of low quality filtered in the pre-processing phase. There is no limit to the number of cells, the only limit is perhaps the computer's memory.

As for the error you encountered, it concerns one of the parallel stages of SCEVAN, so I suggest you try reducing the number of cores with the **_par_cores_** parameter, which is set to 20 cores by default.

Let me know. Thanks. 

Regards

**Comment by StevenTur** [comment]
Hi Antonio,

I still have the same error at 8 cores, do you have a suggestion ?

Here are my computer composant : 
![image](https://user-images.githubusercontent.com/106545864/186436300-f164b038-699d-4e24-bb95-d4eafd20f7a1.png)

Steven

**Comment by StevenTur** [comment]
I tried 4 too :

![image](https://user-images.githubusercontent.com/106545864/186445136-8b0c7df8-2de1-41c9-b8f0-63529eebfbcc.png)

**Comment by StevenTur** [comment]
Hi Antonio,

It finally works for all my cells, but there are some missing outputs. 

I did a test before on 1000 cells and I got these volcanoes for all chrosmosomes:

![image](https://user-images.githubusercontent.com/106545864/186716994-2eef1f2f-4a6e-438d-8253-396b21014492.png)


Which is really nice but i dont get it for my 21000 cells.

However, I never got these figures : 

![image](https://user-images.githubusercontent.com/106545864/186717188-55728d1f-f33b-49a3-afe8-8244695c0406.png)


But this is a really good start. 

I have another question. Is it possible to tell the program to be less strict in defining tumor cells? I have a population that has a small mutation and is not defined as a tumor cell.

Here is the pipelin i have run :

testData <-
  readRDS("TALL_4_Rv2PAGA_exp.rawdata.RDS")
Scevan <- SCEVAN::pipelineCNA(testData,
                              sample = "TALL",
                              par_cores = 8,
                              plotTree = TRUE,
                              ClonalCN = TRUE,
                              SUBCLONES = TRUE,
                              organism = "mouse")
saveRDS(Scevan, file = "SCEVAN.test.RDS")


Thanks for your help,

Steven

**Comment by AntonioDeFalco** [comment]
Hi @StevenTur,
I am glad if you managed to execute, if I can know how you solved it.

If you reinstall SCEVAN you can use the function added in the last commit, to obtain that plot:
  **_plotAllSubclonalCN(sample = "TALL")_**

I am sorry, but at the moment we do not have a parameter for a less strict classification. But if you have an already known classification of which cells are normal, you can try using the **_norm_cell_** parameter in which you pass a vector of all normal cells.

Thanks. Regards.

**Comment by hai178912522** [comment]
Hi,Antonio,
thanks for the resolution.
but I met trouble in the function of the comparison.I have reinstalled the packages.But still can't import the function
![image](https://user-images.githubusercontent.com/59815858/187360331-5cea52bd-3339-4013-94cb-422b5af3a20f.png)

**Comment by AntonioDeFalco** [comment]
> Hi,Antonio, thanks for the resolution. but I met trouble in the function of the comparison.I have reinstalled the packages.But still can't import the function ![image](https://user-images.githubusercontent.com/59815858/187360331-5cea52bd-3339-4013-94cb-422b5af3a20f.png)

Hi @hai178912522 ,
This is strange, try with devtools::install_github("AntonioDeFalco/SCEVAN", **force = TRUE**) or first uninstall SCEVAN and then reinstall it. 

Let me know. Regards

**Comment by hai178912522** [comment]
> 
Hi， Antonio.Thanks so much for your reply.
I tryed both devtools::install_github("AntonioDeFalco/SCEVAN", force = TRUE) and  uninstall then reinstall  SCEVAN .but it still doesn't work.I can use the fuction pipelineCNA but not the comparsion .
![image](https://user-images.githubusercontent.com/59815858/187850821-8467b95e-ecd7-4664-81f4-324c84886bd7.png)
Anybody met the same question ?

**Comment by zyb1984** [comment]
Why when I set "par_cores=1", also with error message for "Error in mclapply(1:totChr, getMajorityCall, mc.cores = par_cores) : 'Mc.cores' > 1 is not supported by Windows" 
![image](https://user-images.githubusercontent.com/24197491/189593709-f4a1be0d-0118-4395-8e20-21d8488b80a6.png)

 
![image](https://user-images.githubusercontent.com/24197491/189593606-a7530558-2337-4245-a210-e387f4cf2d38.png)







,

**Comment by AntonioDeFalco** [comment]
> Why when I set "par_cores=1", also with error message for "Error in mclapply(1:totChr, getMajorityCall, mc.cores = par_cores) : 'Mc.cores' > 1 is not supported by Windows"

Hi @zyb1984, thanks for the report I fixed it in the last commit [b7effc2](https://github.com/AntonioDeFalco/SCEVAN/commit/b7effc2eb0f9c85c81dccaf89c048e66897d38dd). 
Reinstall SCEVAN and let me know if it's ok now.

Regards.

**Comment by zyb1984** [comment]
Thank you very much.

**Comment by Phoenix12580** [comment]
Thank you very much.

**Comment by zhangpebbels** [comment]
hi,[AntonioDeFalco. when i run pipelineCNA ,it comes the  trouble"
Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], Subclones = pred) :
  arguments imply differing number of rows: 0, 44
In addition: There were 22 warnings (use warnings() to see them)"
Could you help me on the trouble? Thanks a lot .

**Comment by AntonioDeFalco** [comment]
Answered in https://github.com/AntonioDeFalco/SCEVAN/issues/42
