### ISSUE TITLE
Did the count_mtx include stromal cells 

### ISSUE THREAD

**Issue by cystone** [AntonioDeFalco/SCEVAN#28]
As the question. When we input the count_mtx. Do we have to extract the epithelial cells before the SCEVAN process, or do we input the whole count_mtx including immune cells endothelium and fibroblasts. Thanks for your excellent scRNAseq tools.

**Comment by AntonioDeFalco** [comment]
Hi @cystone, 
Thanks for your interest in our tool. Yes you have to input the whole count_mtx including immune cells endothelium etc.. and SCEVAN classify normal and tumor cells and then perform the entire analysis. In the case of already known normal cells, you can pass the vector of their names as parameter _**norm_cells**_. 

I hope this is clear.
