### ISSUE TITLE
Residual example dataset produced

### ISSUE THREAD

**Issue by alhafidzhamdan** [AntonioDeFalco/SCEVAN#3]
Hi there,

These files keep getting produced even if I'm running my own samples. Looks like the example dataset.

mgh125_plotcnaline2.RData
testSpecificAlteration_MGH125.RData
diffSubclonesMGH125.RData

A

**Comment by AntonioDeFalco** [comment]
Hi,
I removed in the last commit ([b218a32](https://github.com/AntonioDeFalco/SCEVAN/commit/05f4b1396149b77d6882f37ec3eeb4ea9eb01018)) some code typos that saved intermediate pipeline data for debugging.

Thanks again. Regards
