### ISSUE TITLE
Error!  smooth data

### ISSUE THREAD

**Issue by weipingz** [AntonioDeFalco/SCEVAN#30]
Hi, I encountered the following error when I used the code:` results <- SCEVAN::pipelineCNA(p1012_rawcount, sample = "P1012", par_cores = 8, SUBCLONES = TRUE, plotTree = TRUE)`
I was puzzled about the reason for the error. Do you have any suggestions? Looking forward to your reply. Thank you very much!
The record is as follows：
[1] "found 30 confident non malignant cells"
[1] "7897 genes annotated"
[1] "4) Filter: genes involved in the cell cycle"
[1] "7474 genes past filtering "
[1] "5)  Filter: cells > 5genes per chromosome "
[1] "6) Log Freeman Turkey transformation"
[1] "A total of 6865 cells, 7474 genes after preprocessing"
[1] "7) Measuring baselines (confident normal cells)"
[1] "8) Smoothing data"
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  ignoring SIGPIPE signal
Calls: <Anonymous> ... classifyTumorCells -> <Anonymous> -> lapply -> FUN -> sendMaster
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  ignoring SIGPIPE signal
Calls: <Anonymous> ... classifyTumorCells -> <Anonymous> -> lapply -> FUN -> sendMaster
Error in sendMaster(try(lapply(X = S, FUN = FUN, ...), silent = TRUE)) : 
  ignoring SIGPIPE signal
Calls: <Anonymous> ... classifyTumorCells -> <Anonymous> -> lapply -> FUN -> sendMaster

**Comment by AntonioDeFalco** [comment]
Hi @weipingz 

The error regard the parallel phase of mclapply.  You run the code in Rstudio interactive session or Rscript? What is your version of R? Have you tried using fewer cores ?

Thanks.

**Comment by weipingz** [comment]
> Hi @weipingz
> 
> The error regard the parallel phase of mclapply. You run the code in Rstudio interactive session or Rscript? What is your version of R? Have you tried using fewer cores ?
> 
> Thanks.

I run the code in Rscript. The version of R is 4.2.0. 
R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

when I used fewer cores and fewer cells, the Smoothing data is not broken. However, there is another error.
[1] "found 3 subclones"
percentage_cells_subsclone_1 percentage_cells_subsclone_2 
                   0.2631579                    0.4210526 
percentage_cells_subsclone_3 
                   0.3157895 
[1] "Segmentation of subclone :  1"
[1] "Segmentation of subclone :  2"
[1] "Segmentation of subclone :  3"
.....
$P1012_shareSubclone
                 Chr     Start       End Alteration segm.mean sh_sub Mean
P1012_share1.4     1  31906421  87109998          2  0.186914    1-3    0
P1012_share2.7     1 121087345 151195321         -2 -0.129066    2-3    0
P1012_share1.10    1 156750610 162599842         -1 -0.142451    1-3    0
P1012_share1.17    2  46580937  85545280          1  0.133494    1-2    0
P1012_share2.16    2 127257290 158862958         -1 -0.124088    2-3    0
P1012_share1.40    4  82430562 189963204         -2 -0.147532    1-2    0
P1012_share3.37    4  83261536 173377532         -2 -0.301391    3-2    0
P1012_share1.45    5    196871  14871778          2  0.123764    1-3    0
P1012_share2.34    5 132750817 141636870          2  0.269448    2-3    0
P1012_share1.52    6    291630  16761491         -1 -0.080842    1-2    0
P1012_share1.59    6 136342281 144095573          2  0.193894    1-2    0
P1012_share1.61    6 158650014 170584692          2  0.200421    1-2    0
P1012_share1.67    7 102456238 158956747         -2 -0.196876    1-2    0
P1012_share1.69    8    406428  42897290         -2 -0.393336    1-2    0
P1012_share1.82   10  87863113 114174220         -2 -0.173818    1-3    0
P1012_share1.85   11    167784    867116          2  0.246251    1-2    0
P1012_share1.87   11   9138825  17349974         -1 -0.113631    1-3    0
P1012_share1.89   11  59208510  61161617         -1 -0.143251    1-2    0
P1012_share1.100  12  57516588  89353271          2  0.550808    1-2    0
P1012_share1.106  13  19633681  30764426         -2 -0.072500    1-2    0
P1012_share2.89   13  19633681  29850684         -2 -0.146439    2-1    0
P1012_share1.121  16     46407   3539048          2  0.358971    1-2    0
P1012_share1.126  16  31713229  57083531         -2 -0.189237    1-2    0
P1012_share1.130  17    439978   4786433         -2 -0.213226    1-2    0
P1012_share1.132  17  30477362  36212878         -2 -0.164529    1-2    0
P1012_share1.156  20    296968   5950558         -2 -0.189302    1-2    0
P1012_share2.138  20    296968   5950558         -1 -0.163175    2-1    0
P1012_share2.152  22  42615244  50783663         -2 -0.210188    2-1    0

Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], Subclones = pred) : 
 Parameter values mean different number of rows : 0, 38
Calls: <Anonymous> -> subcloneAnalysisPipeline -> plotTSNE -> data.frame

**Comment by weipingz** [comment]
> Hi @weipingz
> 
> The error regard the parallel phase of mclapply. You run the code in Rstudio interactive session or Rscript? What is your version of R? Have you tried using fewer cores ?
> 
> Thanks.

Hi, when I 

> > Hi @weipingz
> > The error regard the parallel phase of mclapply. You run the code in Rstudio interactive session or Rscript? What is your version of R? Have you tried using fewer cores ?
> > Thanks.
> 
> I run the code in Rscript. The version of R is 4.2.0. R version 4.2.0 (2022-04-22) -- "Vigorous Calisthenics" Copyright (C) 2022 The R Foundation for Statistical Computing Platform: x86_64-pc-linux-gnu (64-bit)
> 
> when I used fewer cores and fewer cells, the Smoothing data is not broken. However, there is another error. [1] "found 3 subclones" percentage_cells_subsclone_1 percentage_cells_subsclone_2 0.2631579 0.4210526 percentage_cells_subsclone_3 0.3157895 [1] "Segmentation of subclone : 1" [1] "Segmentation of subclone : 2" [1] "Segmentation of subclone : 3" ..... $P1012_shareSubclone Chr Start End Alteration segm.mean sh_sub Mean P1012_share1.4 1 31906421 87109998 2 0.186914 1-3 0 P1012_share2.7 1 121087345 151195321 -2 -0.129066 2-3 0 P1012_share1.10 1 156750610 162599842 -1 -0.142451 1-3 0 P1012_share1.17 2 46580937 85545280 1 0.133494 1-2 0 P1012_share2.16 2 127257290 158862958 -1 -0.124088 2-3 0 P1012_share1.40 4 82430562 189963204 -2 -0.147532 1-2 0 P1012_share3.37 4 83261536 173377532 -2 -0.301391 3-2 0 P1012_share1.45 5 196871 14871778 2 0.123764 1-3 0 P1012_share2.34 5 132750817 141636870 2 0.269448 2-3 0 P1012_share1.52 6 291630 16761491 -1 -0.080842 1-2 0 P1012_share1.59 6 136342281 144095573 2 0.193894 1-2 0 P1012_share1.61 6 158650014 170584692 2 0.200421 1-2 0 P1012_share1.67 7 102456238 158956747 -2 -0.196876 1-2 0 P1012_share1.69 8 406428 42897290 -2 -0.393336 1-2 0 P1012_share1.82 10 87863113 114174220 -2 -0.173818 1-3 0 P1012_share1.85 11 167784 867116 2 0.246251 1-2 0 P1012_share1.87 11 9138825 17349974 -1 -0.113631 1-3 0 P1012_share1.89 11 59208510 61161617 -1 -0.143251 1-2 0 P1012_share1.100 12 57516588 89353271 2 0.550808 1-2 0 P1012_share1.106 13 19633681 30764426 -2 -0.072500 1-2 0 P1012_share2.89 13 19633681 29850684 -2 -0.146439 2-1 0 P1012_share1.121 16 46407 3539048 2 0.358971 1-2 0 P1012_share1.126 16 31713229 57083531 -2 -0.189237 1-2 0 P1012_share1.130 17 439978 4786433 -2 -0.213226 1-2 0 P1012_share1.132 17 30477362 36212878 -2 -0.164529 1-2 0 P1012_share1.156 20 296968 5950558 -2 -0.189302 1-2 0 P1012_share2.138 20 296968 5950558 -1 -0.163175 2-1 0 P1012_share2.152 22 42615244 50783663 -2 -0.210188 2-1 0
> 
> Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], Subclones = pred) : Parameter values mean different number of rows : 0, 38 Calls: -> subcloneAnalysisPipeline -> plotTSNE -> data.frame

Good news! When I increased the number of cells used, the error disappeared!
