### ISSUE TITLE
How to explain clone tree? Could I distinguish the order of subclones by clone tree ?

### ISSUE THREAD

**Issue by weipingz** [AntonioDeFalco/SCEVAN#32]
Thank you for your excellent work! I used the it. And now I get the clone tree.  I also read your article.
As shown below, which subclone  is the progenitor cell? Is it the subclone1?
Or we  can only distinguish the relative relationship of subclones based on the tree?
![P1006CloneTree](https://user-images.githubusercontent.com/50062645/190549687-93db9f79-0747-44d7-9402-50309029440c.png)

**Comment by AntonioDeFalco** [comment]
Hi @weipingz,
No, the output is a tree without roots, subclone 1 is not the root. With this tree you can observe the relationship and distance between the subclones and try to understand the temporal evolution e.g. if you have no temporal information of the analysed cells based on the increase of alterations in the different subclones (if you don't have temporal information on the analysed cells in the matrix).

Thanks. Regards.

**Comment by weipingz** [comment]
Thank you for your answer!
