### ISSUE TITLE
Prepration of listCountMtx from merged Seurat object and erro with reporting "Bad sample low cells < 15" and 

### ISSUE THREAD

**Issue by vailin1992** [AntonioDeFalco/SCEVAN#33]
**Dear AntonioDeFalco,
        Thank you for the great works! 👍👍👍**
        
**I am very interesting in this tool. I have several questions listed as follow. I am dealing with a merged Seurat object with more than 50 samples. I have refered the data structure of sample data listCountMtx, which looks like this:**

![1663384778947](https://user-images.githubusercontent.com/41881792/190838623-0d362009-95b4-402b-94ae-a301816ed335.png)

**I tried to get my listCountMtx from the merged Seurat object "" with the following code:**
split_sce.Epi <- SplitObject(sce.Epi, split.by = "orig.ident")
count_mtx_list <- list()
for (i in 1:length(split_sce.Epi)) {
  count_mtx_list[i] <- split_sce.Epi[[i]]@assays$RNA@counts
  names(count_mtx_list)[i] <- split_sce.Epi[[i]]$orig.ident[[1]]
}

**And I got my listCountMtx looks like this:**

![d134fd0ba727901984beb72adf8ae43](https://user-images.githubusercontent.com/41881792/190838783-2cfa7e4b-cef1-4c3b-bfb1-b7fd6b2ff510.png)

**The structure of my is slightly different from the sample listCountMtx, but it did work with the following code:**
results <- SCEVAN::multiSampleComparisonClonalCN(count_mtx_list, analysisName = "all", organism = "human" , par_cores = 32)

**We successfully deal several samples until it reported erro  with "Error in preprocessingMtx(count_mtx, sample, par_cores = par_cores, findConfident = normalNotKnown,  : Bad sample low cells < 15 In addition: Warning messages: 1: In asMethod(object) :
sparse->dense coercion: allocating vector of size 1.1 GiB 2: In asMethod(object) : sparse->dense coercion: allocating vector of size 1.1 GiB"**

![4109ccf277f349ea7847e40f57deb8e](https://user-images.githubusercontent.com/41881792/190838875-5afc41e1-a2cc-4593-b146-65e11873538a.png)

My questions are: 
1. Does it means that the cell number of each sample should not less than 15 and these samples should be excluded before running.
2. The procedure of my prepration of listCountMtx from the merged Seurat object is correct or not.

        I would be grateful if you can help with me! Looking forward to hear from you soon! Thank you!

        Yours sincerely

Dr. Wang-Zhong Li
National Clinical Research Center for Respiratory Disease

**Comment by vailin1992** [comment]
Sorry for missing another point, does the input should include all cells but not limited to epithelial cell. I have noticed the disscussion in #28 . I also leared from your manuscript preprint that a set of high confident non-malignant cells are identified and used to determine a copy number baseline and to compute the relative matrix removing the baseline (Steps A and B).

**Comment by AntonioDeFalco** [comment]
Hi @vailin1992,

> 2\. The procedure of my prepration of listCountMtx from the merged Seurat object is correct or not. 

Yes, the list of matrices you have is correct, but for a correct pipeline result we set a minimum limit of 15 cells for the samples. In this case you have, as I can see, a matrix with 17 cells which after the initial filtering has a cell count of less than 15. 

> 1. Does it means that the cell number of each sample should not less than 15 and these samples should be excluded before running.

Exactly you should remove this sample from the list to get the result. If it is considered appropriate to analyse matrices with such a small number of cells, we could make the minimum number of cells a flexible parameter in a future update of our tool.

> Sorry for missing another point, does the input should include all cells but not limited to epithelial cell. I have noticed the disscussion in #28 .

Yes the input must include all cells. 

>  I also leared from your manuscript preprint that a set of high confident non-malignant cells are identified and used to determine a copy number baseline and to compute the relative matrix removing the baseline (Steps A and B).

It's correct.

Thanks for you interest. Regards.

**Comment by Drjingluo** [comment]
Hi,@AntonioDeFalco,
I used the above script but meet an error in Step 9. Can you help me ?

results <- SCEVAN::multiSampleComparisonClonalCN(count_mtx_list, analysisName = "all", organism = "human" , par_cores = 48)

[1] " raw data - genes: 33691 cells: 1351"
[1] "1) Filter: cells > 200 genes"
[1] "low data quality"
[1] "2) Filter: genes > 5% of cells"
[1] "6734 genes past filtering"
[1] "3) Annotations gene coordinates"
[1] "found 30 confident non malignant cells"
[1] "6455 genes annotated"
[1] "4) Filter: genes involved in the cell cycle"
[1] "6129 genes past filtering "
[1] "5)  Filter: cells > 5genes per chromosome "
[1] "6) Log Freeman Turkey transformation"
[1] "A total of 1234 cells, 6129 genes after preprocessing"
[1] "7) Measuring baselines (confident normal cells)"
[1] "8) Smoothing data"
[1] "9) Segmentation (VegaMC)"
[1] "10) Adjust baseline"
[1] "11) plot heatmap"
[1] "found 688 tumor cells"
[1] "time classify tumor cells:  1.22660799423854"
[1] " raw data - genes: 33691 cells: 3000"
[1] "1) Filter: cells > 200 genes"
[1] "low data quality"
[1] "2) Filter: genes > 5% of cells"
[1] "7392 genes past filtering"
[1] "3) Annotations gene coordinates"
[1] "found 30 confident non malignant cells"
[1] "7086 genes annotated"
[1] "4) Filter: genes involved in the cell cycle"
[1] "6705 genes past filtering "
[1] "5)  Filter: cells > 5genes per chromosome "
[1] "6) Log Freeman Turkey transformation"
[1] "A total of 2928 cells, 6705 genes after preprocessing"
[1] "7) Measuring baselines (confident normal cells)"
[1] "8) Smoothing data"
[1] "9) Segmentation (VegaMC)"
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 6705, 5588
In addition: Warning messages:
1: In parallel::mclapply(1:ncol(count_mtx_relat), nonLinSmooth, mc.cores = par_cores) :
  scheduled cores 1, 5, 15, 18, 22, 25, 26, 32 did not deliver results, all values of the jobs will be affected
2: In matrix(unlist(test.mc), ncol = ncol(count_mtx_relat), byrow = FALSE) :
  data length [16360200] is not a sub-multiple or multiple of the number of rows [5588]
