### ISSUE TITLE
Can I get a PDF of the results？

### ISSUE THREAD

**Issue by boasong** [AntonioDeFalco/SCEVAN#34]
The default output result pictures are in png format. How can I get the result pictures in pdf format? Any help would be highly appreciated!

**Comment by AntonioDeFalco** [comment]
Hi @boasong ,
With the next code example, you can obtain a final pdf report of all generated png plots:

```
sample <- "MGH106"
files <- list.files("./output/", pattern = sample)
files <- files[grepl(".png", files)]
timeFiles <- lapply(files, function(x) file.mtime(paste0("./output/",x)))
files <- paste0("./output/",files[order(unlist(timeFiles))])

library(magick)

all_images_1 <- purrr::reduce(
  purrr::map(files,image_read),
  c
)
image_write(all_images_1 , format = "pdf", paste0("./output/", sample, ".pdf"))
```
Let me know if it is ok and if the result is as desired.

Regards.

**Comment by boasong** [comment]
Thank you for your method, but I want an editable pdf image. Unfortunately, the details of the pdf obtained by referring to the method you provided cannot be edited with software such as AI.
Is the image that can be set during pipelineCNA editable in pdf format?
Thank you for your reply

**Comment by boasong** [comment]
> Hi @boasong , With the next code example, you can obtain a final pdf report of all generated png plots:
> 
> ```
> sample <- "MGH106"
> files <- list.files("./output/", pattern = sample)
> files <- files[grepl(".png", files)]
> timeFiles <- lapply(files, function(x) file.mtime(paste0("./output/",x)))
> files <- paste0("./output/",files[order(unlist(timeFiles))])
> 
> library(magick)
> 
> all_images_1 <- purrr::reduce(
>   purrr::map(files,image_read),
>   c
> )
> image_write(all_images_1 , format = "pdf", paste0("./output/", sample, ".pdf"))
> ```
> 
> Let me know if it is ok and if the result is as desired.
> 
> Regards.

**Comment by hzaumsq** [comment]
@boasong Have you solved this problem， I also want to get the editable pdf image
