### ISSUE TITLE
Error in f(...): Graphics API version mismatch

### ISSUE THREAD

**Issue by MrClearLovez** [AntonioDeFalco/SCEVAN#37]
Dear Mr. AntonioDeFalco,
Yesterday I tried to run the pipelineCNA function, but I get this error.I tried to fix it for a day and didn't get it.Sincerely request your answer!
![image](https://user-images.githubusercontent.com/103395438/193171515-30c7ae69-ca8e-4868-a61a-277f71e4591e.png)

I use R version is 4.2.0. First,I think  my ggplot2 version is too old, so I try to re-install it, but still can't solve. Sincerely request your answer!

**Comment by AntonioDeFalco** [comment]
Hello, 
Have you tried reinstalling the ragg package yet? The error seems to be related to updating to R 4.2 with some old graphics package.

`install.packages("ragg")`

Thanks for the interest. Regards.

**Comment by MrClearLovez** [comment]
Dear AntonioDeFalco,
I rereinstall this package and sovled this problem.Thanks you very much for your help.


But,I get some warning.I wonder if these warnings affected the results.These warnings are as follows:



and this:

what's more:



Thanks for your help again!
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntonioDeFalco/SCEVAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntonioDeFalco/SCEVAN] Error in f(...): Graphics API version mismatch (Issue #37)





 
Hello,
 Have you tried reinstalling the ragg package yet? The error seems to be related to updating to R 4.2 with some old graphics package.
 
install.packages("ragg")
 
Thanks for the interest. Regards.

**Comment by MrClearLovez** [comment]
Dear Mr. AntonioDeFalco,
I have another question,that is piplineCNA function results$class,I found 3 class cells.I wonder if filtered cells are normal cells?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntonioDeFalco/SCEVAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月30日(星期五) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntonioDeFalco/SCEVAN] Error in f(...): Graphics API version mismatch (Issue #37)





 
Hello,
 Have you tried reinstalling the ragg package yet? The error seems to be related to updating to R 4.2 with some old graphics package.
 
install.packages("ragg")
 
Thanks for the interest. Regards.

**Comment by AntonioDeFalco** [comment]
> But,I get some warning.I wonder if these warnings affected the results.These warnings are as follows: and this: what's more:

I can't see the warnings in your answer, but they can hardly affect the outcome.

> I have another question,that is piplineCNA function results$class,I found 3 class cells.I wonder if filtered cells are normal cells?

The filtered cells are low quality cells that are filtered out and not used in the pipeline.

**Comment by MrClearLovez** [comment]
Truly appreciate your timely help.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AntonioDeFalco/SCEVAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月4日(星期二) 晚上6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [AntonioDeFalco/SCEVAN] Error in f(...): Graphics API version mismatch (Issue #37)





  
But,I get some warning.I wonder if these warnings affected the results.These warnings are as follows: and this: what's more:
  
I can't see the warnings in your answer, but they can hardly affect the outcome.
  
I have another question,that is piplineCNA function results$class,I found 3 class cells.I wonder if filtered cells are normal cells?
  
The filtered cells are low quality cells that are filtered out and not used in the pipeline.
