### ISSUE TITLE
SCEVAN 

### ISSUE THREAD

**Issue by kk525liu** [AntonioDeFalco/SCEVAN#38]
when I was run 
 results <- SCEVAN::pipelineCNA(count_mtx_CR, sample = "CRPC",SUBCLONES = T,par_cores = 35)  
,the following error occurred

[1] "found 4 subclones"
percentage_cells_subsclone_1 percentage_cells_subsclone_2 percentage_cells_subsclone_3 
                   0.3577128                    0.3098404                    0.2021277 
percentage_cells_subsclone_4 
                   0.1303191 
[1] "Segmentation of subclone :  1"
[1] "Segmentation of subclone :  2"
[1] "Segmentation of subclone :  3"
[1] "Segmentation of subclone :  4"
Error in data.frame(..., check.names = FALSE) : 
  (converted from warning) row names were found from a short variable and have been discarded

 I checked my row name and column name, and there is no duplicate value
when I was run 
 results <- SCEVAN::pipelineCNA(count_mtx_CR, sample = "CRPC",SUBCLONES = F,par_cores = 35)  
there is no error
How can I solve this error when "SUBCLONES = T"

**Comment by Crick0509** [comment]
hei,I have the same problem.waiting for the key

**Comment by kk525liu** [comment]
My solution is to minimize the number of cores used，and it worked



At 2023-01-05 10:36:59, "Crick0509" ***@***.***> wrote:

hei,I have the same problem.waiting for the key

**Comment by Crick0509** [comment]
thankyou very much!!
