### ISSUE TITLE
Questions about Oncoheat plot

### ISSUE THREAD

**Issue by StevenTur** [AntonioDeFalco/SCEVAN#39]
Hi fernando,

I have a question about that output : 

What is the meaning and the difference between AMP and GAIN and LOSS and DEL ?

Steven

**Comment by AntonioDeFalco** [comment]
Hi @StevenTur,
In the copy number call added in recent updates, SCEVAN try to infer the integer CN from the log ratio CN inferred from the scRNA data. SCEVAN classifies each alteration with the following labels:

- **AMP**: Addition of 2 copies
- **GAIN**: Addition of 1 copy
- **LOSS**: Loss of 1 copy
- **DEL**: Complete loss

Regards.

**Comment by StevenTur** [comment]
Thank you for your answer.

When you said one copy, do you mean gene? 

If I have for example a chromosome twelve trisomy, how will this be indicated? Will it appear as a GAIN? And for a tetrasomy an AMP?

Steven

**Comment by AntonioDeFalco** [comment]
> When you said one copy, do you mean gene?

Yes, I am referring to a copy of the genes belonging to the interval that has an alteration.

> If I have for example a chromosome twelve trisomy, how will this be indicated? Will it appear as a GAIN? And for a tetrasomy an AMP?

Yes, exactly.
