### ISSUE TITLE
error when running multiSampleComparisonClonalCN

### ISSUE THREAD

**Issue by charlenesp** [AntonioDeFalco/SCEVAN#41]
Hi, thank you for developing this wonderful tool! I have two questions related to multisample processing:

1) Error in comparison
I got this error below when I processed 9 samples using the multiSampleComparisonClonalCN.

My code:
`results <- SCEVAN::multiSampleComparisonClonalCN(listCountMtx, analysisName = "all", organism = "mouse" , par_cores = 50)`

This error pops up after all 9 samples got their individual heatmap, but before the comparison output (compareClonalCN.png or OncoHeat.png):
```
Error in posSta:posEnd : argument of length 0
Calls: <Anonymous> -> annoteBandOncoHeat -> [ -> [.data.frame
```

2) Plot size
When processing multiple samples, sometimes the compareClonalCN.png or OncoHeat.png plots got squeezed or partially cut off when there're many samples. How do I rescale/resize them?

**Comment by AntonioDeFalco** [comment]
Thanks for your interest. I fixed it in the last commit. Reinstall SCEVAN with the latest commit and let me know if the display is now OK.

Sorry for the delay. Regards.
