### ISSUE TITLE
Error and Question

### ISSUE THREAD

**Issue by StevenTur** [AntonioDeFalco/SCEVAN#42]
Hi Antonio,

I add the fonction you said to me here to have the volcanoes plots : 

![Screen Shot 2022-10-13 at 3 43 47 PM](https://user-images.githubusercontent.com/106545864/195694597-5975f196-b068-42c3-90fc-22d211f5110f.png)

And i got that mistake : 

![Screen Shot 2022-10-13 at 3 26 42 PM](https://user-images.githubusercontent.com/106545864/195694646-f565fe27-8e1e-4cfa-8a6b-4c343ef4440e.png)

Also, sometimes depends on my input i don't have all the output like the tree, vulcanoes, or copy number subclones (log ratio).

I was wondering also if is it possible to have the access to the code to plot the Tsne subclones map in order to personalize it ?

Thank you again for your help, it looks really good !

Steven

**Comment by AntonioDeFalco** [comment]
Hi @StevenTur,

The function for plotting the copy number of each subclone in a single figure _**plotAllSubclonalCN**_ can be used after running the pipeline, not including it as a parameter when using pipelineCNA as you did. So you must first run _**pipelineCNA**_(testData, sample = "TALL".. etc.) and then _**plotAllSubclonalCN**_("TALL")

> Also, sometimes depends on my input i don't have all the output like the tree, vulcanoes, or copy number subclones (log ratio).

If you do not get this type of output concerning subclonal analysis, it means that no subclones are found within the scRNA-seq matrix.

> I was wondering also if is it possible to have the access to the code to plot the Tsne subclones map in order to personalize it ?

All the code is public here on github and can be customised as desired.

Sorry for the delay. Regards
