### ISSUE TITLE
About 80% of cells were classified as "tumor" for a PBMC sample

### ISSUE THREAD

**Issue by YiweiNiu** [AntonioDeFalco/SCEVAN#44]
Hi,

Thanks for this great work.

Recently, I tested SCEVAN using a PBMC sample of a gastric cancer patient, and found that about 80% of cells were labeled as "tumor".

```r
> results %>% group_by(class) %>% summarise(n = n()) %>% mutate(prop = n/sum(n)*100)
# A tibble: 3 x 3
  class        n  prop
  <chr>    <int> <dbl>
1 filtered    49  1.24
2 normal     745 18.8 
3 tumor     3163 79.9
```

However, no epithelial cells were found in this PBMC sample.

Do you have any clues about this? Also, I wonder whether SCVAN can be applied to metastasis-positive lymph nodes, where the fraction of epithelial cells may be very low.

Bests,
Yiwei

**Comment by AntonioDeFalco** [comment]
Hi @YiweiNiu,

> Do you have any clues about this?

SCEVAN was designed for analysing scRNA data with malignant cells, which is why it assumes the presence of cancer cells in the sample. This can lead to errors when analysing matrices of only normal cells. What is the purpose of the analysis, how come you analysed this type of matrix? 

> Also, I wonder whether SCVAN can be applied to metastasis-positive lymph nodes, where the fraction of epithelial cells may be very low.

Yes, I believe that SCEVAN can be applied. It has proven in analyses that it classifies well even in samples with very high tumour purity. 

Thanks for your interest. Please let me know.

Bests.

**Comment by YiweiNiu** [comment]
Thank you for your reply.

> What is the purpose of the analysis, how come you analysed this type of matrix?

I just want to test SCEVAN. 

I am confused about this. If SCEVAN finds cancer cells in a sample without epithelial cells, how can I trust its results when I want to know whether a sample contains malignant cells? The user just cannot determine whether the results are false-positives.

> Yes, I believe that SCEVAN can be applied. It has proven in analyses that it classifies well even in samples with very high tumour purity.

In metastasis-positive lymph nodes, the fraction of cancer cells can be very low. Therefore, tumor purity (the percent of cancer cells present in a sample of tumor tissue) is low. If I understand this correctly.

Sorry if my questions are a bit basic.

**Comment by AntonioDeFalco** [comment]
> I am confused about this. If SCEVAN finds cancer cells in a sample without epithelial cells, how can I trust its results when I want to know whether a sample contains malignant cells? The user just cannot determine whether the results are false-positives.

Thanks for the suggestion, we can improve the method for the case of tumor purity = 0, but as I said, the error stems from the fact that we assume that there are tumor cells in the analysed matrix.

> In metastasis-positive lymph nodes, the fraction of cancer cells can be very low. Therefore, tumor purity (the percent of cancer cells present in a sample of tumor tissue) is low. If I understand this correctly.

Sorry for the mistake, I meant to say that in the analysis done SCEVAN works well also with very low tumour purity. In our work we analyse HNSCC dataset which contain corresponding lymph node metastases, and SCEVAN works well on this kind of data:

![Screenshot 2022-11-20 at 12 46 53](https://user-images.githubusercontent.com/11536289/202900206-36c27fe8-14ef-4844-a89a-d812542f0257.png)

Thanks. Regards.

**Comment by YiweiNiu** [comment]
Thanks a lot for your help. I understand this now.
