### ISSUE TITLE
package ‘SCEVAN-main’ not installed because it is not built for UCRT

### ISSUE THREAD

**Issue by Phoenix12580** [AntonioDeFalco/SCEVAN#47]
My R version is 4.2.1.
How to fix it? Thank you very much

**Comment by AntonioDeFalco** [comment]
Hello @Phoenix12580  thanks for your interest, I tried to install SCEVAN on an R 4.2.1 version and the installation finished without errors. What operating system are you using? Did you use devtools for the installation? 

Regards

![Screenshot 2023-02-20 at 10 21 54](https://user-images.githubusercontent.com/11536289/220064791-62445b98-6bde-40e2-8bcc-6335c24d4a80.png)

**Comment by Phoenix12580** [comment]
Thank you for your reply ， I searched this error message and found that R 4.2 version for windows caused this error. 
https://github.com/ManuelHentschel/vscDebugger/issues/182  explained this error:The error relates to the UCRT runtime that is used starting from version 4.2 to support native UTF-8 encoding for Windows.
I installed SCEVAN in R 4.1 version was OK.

**Comment by miccec** [comment]
issue solved
