### ISSUE TITLE
Is it advisable to run SCEVAN on a count matrix with cells from multiple samples?

### ISSUE THREAD

**Issue by jingxinfu** [AntonioDeFalco/SCEVAN#5]

**Comment by AntonioDeFalco** [comment]
Running _**pipelineCNA**_ of SCEVAN on a matrix with multiple samples could be useful if the samples come from the same patient to compare e.g. clonal structure in multi-regional or temporal samples. 

In the case of samples from different patients the inference of copy number alterations may not be exactly correct using a unique reference of normal cells during the pipeline. For this reason it would be more appropriate to run SCEVAN for each patient and then compare the results, an example currently available is the comparison of two samples with the function _**compareClonalStructure**_, which we plan to extend to compare more samples.

What is your case? Thanks for your interest. 

Regards

**Comment by jingxinfu** [comment]
Thank you for your kind instruction! looking forward to the updated version of `compareClonalStructure` compatible with more than 2 samples!

**Comment by AntonioDeFalco** [comment]
Hello @jingxinfu,
If you are interested we have included a function for the automatic analysis of multiple samples (**multiSampleComparisonClonalCN**) you can find the details in the README.

Best Regards
