### ISSUE TITLE
OncoHeat plot

### ISSUE THREAD

**Issue by orange-3711** [AntonioDeFalco/SCEVAN#51]
Hi @AntonioDeFalco 

The resulting picture information overlaps due to height and width limitations. I want to customize my drawing, How can I get the data in a oncoheat drawing?

I would appreciate it if you could tell me how to do it.

**Comment by AntonioDeFalco** [comment]
Hi @orange-3711,
In the output folder you can found the file "**_SAMPLE_NAME_SubcloneDiffAnalysis.RData_**" which contain the data frame _**diffSubcl**_ with the information on the copy number alteration difference between the subclones. It contains chromosome and alteration position, if you want the annotation by chromosome band and get the data frame used to create the oncoheat plot you can reinstall SCEVAN and use the _**annoteBandOncoHeat**_ function as follows:

```
load("./output/ MGH106_SubcloneDiffAnalysis.RData")
load("./output/MGH106_count_mtx_annot.RData")
library(SCEVAN)
OncoHeat <- annoteBandOncoHeat(count_mtx_annot, diffSubcl, nSub = sum(grepl("subclone", names(diffSubcl))), organism = "human")
```

**Comment by AntonioDeFalco** [comment]
@orange-3711 I also added in the last commit  [4f818bd](https://github.com/AntonioDeFalco/SCEVAN/commit/4f818bd93367c83701a4749e5a1335cdbeed093c) the automatic saving of the final data frame **_oncoHeat_** and the picture (plotHeatmapOncoHeat) created with pheatmap in the file **_SAMPLE_NAME_PlotOncoHeat.RData_**, which you can display with:

`
plot(plotHeatmapOncoHeat$gtable)
`

**Comment by orange-3711** [comment]
> 

Sorry, I didn't describe my problem clearly. I want to apply it to multisample analysis. Is it also applicable?

**Comment by orange-3711** [comment]
> @orange-3711 I also added in the last commit [4f818bd](https://github.com/AntonioDeFalco/SCEVAN/commit/4f818bd93367c83701a4749e5a1335cdbeed093c) the automatic saving of the final data frame **_oncoHeat_** and the picture (plotHeatmapOncoHeat) created with pheatmap in the file **_SAMPLE_NAME_PlotOncoHeat.RData_**, which you can display with:
> 
> `load("./output/MGH106_PlotOncoHeat.RData") plot(plotHeatmapOncoHeat$gtable)`

@AntonioDeFalco  Sorry, I didn't describe my problem clearly. I want to apply it to multisample analysis. Is it also applicable?

**Comment by AntonioDeFalco** [comment]
> > @orange-3711 I also added in the last commit [4f818bd](https://github.com/AntonioDeFalco/SCEVAN/commit/4f818bd93367c83701a4749e5a1335cdbeed093c) the automatic saving of the final data frame **_oncoHeat_** and the picture (plotHeatmapOncoHeat) created with pheatmap in the file **_SAMPLE_NAME_PlotOncoHeat.RData_**, which you can display with:
> > `load("./output/MGH106_PlotOncoHeat.RData") plot(plotHeatmapOncoHeat$gtable)`
> 
> @AntonioDeFalco Sorry, I didn't describe my problem clearly. I want to apply it to multisample analysis. Is it also applicable?

Yes it also valid for multisample analysis, you will find all in the file **_analysisName_**_PlotOncoHeat.RData.
