### ISSUE TITLE
SCEVAN dataset specific error

### ISSUE THREAD

**Issue by yh154** [AntonioDeFalco/SCEVAN#57]
Dear SCEVAN developer,

I used SCEVAN on two homogenous single cell datasets (i.e. a large dataset broken into two subsets), one ran without any issue, another produced the following error. I will appreciate it very much in you could help to shed some lights on it. Thank you! 

[1] "Segmentation of subclone :  1"
Error in 1:which(df_call$Chromosome == totChr & df_call$End == max(df_call[df_call$Chromosome ==  : 
  NA/NaN argument
Calls: <Anonymous> ... subclonesTumorCells -> getCNcall -> getCallingCN -> [ -> [.data.frame
In addition: There were 11 warnings (use warnings() to see them)

**Comment by AntonioDeFalco** [comment]
Hello @yh154,
This is the first time I have seen this error. I'm sorry but is difficult from the error to understand the problem. 
Is it a public dataset that I can replicate the analysis? Is human or mouse dataset?

**Comment by yh154** [comment]
Dear Antonio,

Sorry for late reply! This mouse data is not published yet, but I'm willing to share the matrix if you are interested. I also find this error only happens when ClonalCN = TRUE. In the meantime, I realized SCEVAN would also classify confident normal cells supplied into tumor/normal/filtered groups. I am wondering what's the rationale behind this? Thank you!

**Comment by AntonioDeFalco** [comment]
> This mouse data is not published yet, but I'm willing to share the matrix if you are interested.

Yes, if you can share it with me, I can try to solve the problem. This is my email: antonio.defalco4@unina.it .

> I realized SCEVAN would also classify confident normal cells supplied into tumor/normal/filtered groups.

If you can explain better what you mean. 

Thank you.

**Comment by AntonioDeFalco** [comment]
Fixed in commit [8048b45](https://github.com/AntonioDeFalco/SCEVAN/commit/8048b45aeae5d76751cf8b76ad3226d469de80f5)
