### ISSUE TITLE
Customisation

### ISSUE THREAD

**Issue by ccruizm** [AntonioDeFalco/SCEVAN#6]
Good day!

Thanks for developing this great tool! I have tested it, and it works well. However, I would like to know how I can add metadata that can be used for visualization purposes. For instance, adding cell identity/cluster in the heatmap plot or exporting the plots in pdf. In addition, how can I add the information generated by SCEVAN (subclones,aneuploidy/diploid results, etc) into a Seurat object to visualize them directly on UMAP or link that info directly to the cells for downstream analysis?

Appreciate in advance any help you can provide.

**Comment by AntonioDeFalco** [comment]
Many thanks for your appreciation and interest in our tool. The customisations you requested are certainly interesting to integrate into the tool, I plan to include soon in a next tool update the possibility to insert metadata in the heatmap plot and the generation of a final pdf report with all generated plots.

As regards the use of the information generated by SCEVAN (aneuploidy/diploid, subclones) in a Seurat object, you can simply add the data.frame returned in output from the pipeline as metadata of the Seurat object in the following way:
 
```
results <- pipelineCNA(count_mtx)

#Create Seurat Object with SCEVAN info
seurObj <- Seurat::CreateSeuratObject(count_mtx, meta.data = results)

#or add SCEVAN info to an existing Seurat object
seurObj <-Seurat::AddMetaData(seurObj, metadata = results)
```
Regards.
