### ISSUE TITLE
Is it possible to derive cells from each subclone

### ISSUE THREAD

**Issue by orange-3711** [AntonioDeFalco/SCEVAN#65]
Hi @AntonioDeFalco 

I wanna to write subclone information into the Seurat, so how am I going to know which cells are in the subclone？

**Comment by AntonioDeFalco** [comment]
In the [README](https://github.com/AntonioDeFalco/SCEVAN) you will find how to integrate the information obtained from SCEVAN into Seurat (including subclones). Very simply:

```
Integration with Seurat
Integration of information obtained with SCEVAN (aneuploidy/diploid, subclones) into Seurat object.

count_mtx : Count matrix of sample.
results <- pipelineCNA(count_mtx)

#Create Seurat Object with SCEVAN info
seurObj <- Seurat::CreateSeuratObject(count_mtx, meta.data = results)

#or add SCEVAN info to an existing Seurat object
seurObj <-Seurat::AddMetaData(seurObj, metadata = results)
```

did you mean this?
