### ISSUE TITLE
Extracting CNV matrix for downstream analysis

### ISSUE THREAD

**Issue by grst** [AntonioDeFalco/SCEVAN#7]
Hi, 

I would like to extract the data used for plotting the  for some downstream analysis (custom visualization and computation of a heterogeneity score). 
<img src="https://user-images.githubusercontent.com/7051479/146949333-e626b716-91c6-46df-86b3-ad4bc48ea764.png" width=500 >

The only full cell x feature matrix I could find in the results is the `mtx_vega.txt` matrix. However when plotting it as a heatmap, the results are rather inconsistent: 

![image](https://user-images.githubusercontent.com/7051479/146950019-9499270a-ae10-45c2-8ea3-7a29fb1b2303.png)

(tumor/normal classification is the result from SCEVAN)

Is there a way to retrieve the "final" SCEVAN results somehow? 

Cheers, 
Gregor 

CC @abyssum

**Comment by AntonioDeFalco** [comment]
Hi, 
Yes the CNV matrix was not saved in the output and the _mtx_vega.txt_ file is an intermediate pipeline file. I added in the last commit [8d91777](https://github.com/AntonioDeFalco/SCEVAN/commit/8d91777d30aaa54d6d4b705aea361cd7fe546376) the saving of the matrix that you will find in the output folder in the file _CNAmtx.RData_.

Thanks for your interest in our tool. Regards

**Comment by grst** [comment]
That was amazingly quick! Thanks!

**Comment by grst** [comment]
Hi @AntonioDeFalco, 

I now ended up with something that looks like this: 
![image](https://user-images.githubusercontent.com/7051479/147109739-da0e2b05-3d7a-4fb5-b269-f4962b0e25c9.png)

which is a lot closer to the SCEVAN heatmap. However, the SCEVAN heatmap seems to have contain some "segmentation" information on top. Is that available somewhere as well?

**Comment by AntonioDeFalco** [comment]
Hi @grst,
If you mean the gray and black colors at the top they indicate the different chromosomes not segmentation information. Instead you can find information about segmentation in the files in the output folder ending with vega output.txt, one file (only tumor) with the segmentation of all tumor cells and one file for each subclone with the respective segmentation.

**Comment by grst** [comment]
I was actually referring to the segments indicated with blue lines here: 

![image](https://user-images.githubusercontent.com/7051479/147336524-b6d17601-cfab-4ba2-b057-8dc2cf4d8001.png)

I suspect this is the same segmentation as in the `vega output.txt` you were mentioning. 
To reproduce the heatmap, do I simply need to calculate the mean of the CNA matrix for each cell in each vega segment?

Many thanks and enjoy the holidays! 
Gregor

**Comment by grst** [comment]
Hi @AntonioDeFalco, 

could you please take a look at my last question? I suspect it got lost over the holidays. 

Many thanks, 
Gregor

**Comment by AntonioDeFalco** [comment]
Hi @grst,
exactly the saved matrix was missing the step of calculating the mean in the segmentation segments. I have corrected it in the last commit [ab634a5](https://github.com/AntonioDeFalco/SCEVAN/commit/ab634a53f349bce694e560a9476de6007e8ec566), now the matrix saved in the CNAmtx.RData file corresponds exactly to the SCEVAN heatmap.

Sorry for the late reply. Regards

**Comment by grst** [comment]
Nice! I now can reproduce the tumor/normal heatmap exactely! 
![image](https://user-images.githubusercontent.com/7051479/149340415-35850f7e-8381-4095-94cf-158fb5d5b0a9.png)

However, the when subsetting it to the subclones, it still looks slightly different. It looks like there is a different segmentation information used for the subclones heatmap: 
![image](https://user-images.githubusercontent.com/7051479/149340808-ebbb6b70-1f8c-40e3-8271-13a15410bd6b.png)

**Comment by AntonioDeFalco** [comment]
@grst I made a mistake in the last commit which caused an error as reported by another user and I have just corrected the problem in the commit. [de6a350](https://github.com/AntonioDeFalco/SCEVAN/commit/960571c17f42f25af54df1fa9f25e62321777062).

**Comment by grst** [comment]
Everything works as expected now! Thanks for your excellent support!

**Comment by Pentayouth** [comment]
Countless softwares have ceased updating shortly after publication. It's very exciting to see the author promptly optimizing such an important and easy-to-use software.
All best wishes!
