### ISSUE TITLE
Single run with multiple samples with normal cells

### ISSUE THREAD

**Issue by ConDem94** [AntonioDeFalco/SCEVAN#70]
Hi,

Thank you for this amazing package!

I have a large integrated (SCVI) dataset with multiple samples 80+ of pancreatic cancer and would like to distinguish malignant from non-malignant cells. I have tried running the multiple sample method but this doesn't allow me to input normal cells and it runs out of memory.

Is it possible to run all of them together and to include normal cells as reference? Here is an example of my code:

```

library(Seurat);library(tidyverse);library(SCEVAN)

# Filter genes: low gene counts and biotypes

pdac.sc <- readRDS("pdac.scvi.annot.rds")


pdac.sc.filt <- subset(pdac.sc, subset = Main_Clusters %in% c("Malignant", "Malignant (mes)", "B", "Mast", "Neutrophils"))

norm_cells <- WhichCells(pdac.sc.filt, idents = c("B", "Mast", "Neutrophils"))

count_matrix <- GetAssayData(pdac.sc.filt, slot="counts")

results <- SCEVAN::pipelineCNA(count_matrix, norm_cell = norm_cells,
                               sample = "PDAC_all", par_cores = 20, SUBCLONES = FALSE, plotTree = TRUE)

```

I would greatly appreciate your help on this!

Best wishes,
Constantinos

**Comment by AntonioDeFalco** [comment]
Hi @ConDem94,
Are you interested in getting only the tumor/normal classification of each sample or also in an automatic copy number profile comparison across samples?

Thanks for your interest and appreciation.

Regards.

**Comment by ConDem94** [comment]
> Hi @ConDem94,
> 
> Are you interested in getting only the tumor/normal classification of each sample or also in an automatic copy number profile comparison across samples?
> 
> 
> 
> Thanks for your interest and appreciation.
> 
> 
> 
> Regards.

Hi Antonio,

I only want the tumour/normal classifications for each sample for now. But it would be good to include normal reference cells to improve the accuracy.


And after I find transcriptomic subtypes, I will analyse them in more detail (look for subclones, compare amp del events).

I look forward to hearing from you.

Best wishes,
Constantinos

**Comment by ConDem94** [comment]
> > I only want the tumour/normal classifications for each sample for now. But it would be good to include normal reference cells to improve the accuracy.
> 
> 
> 
> The best solution is to run pipelineCNA for each sample for example in this way having a named list of raw count matrix of samples to be analysed and a named list of normal reference cells for each sample:
> 
> ```
> 
> 
> 
> resList <- lapply(names(listCountMtx), function(x) {
> 
>         pipelineCNA(listCountMtx[[x]], sample = x, norm_cell = listNormCells[[x]], SUBCLONES = FALSE, 
> 
>             ClonalCN = TRUE, par_cores = 20)
> 
>     })
> 
>  names(resList) <- names(listCountMtx)
> 
> ```
> 
> 
> 
> > I have tried running the multiple sample method but this doesn't allow me to input normal cells and it runs out of memory.
> 
> 
> 
> Yes at the moment multiSampleComparisonClonalCN does not allow the use of normal reference cells it will be added in a next update, and since the function tries to compare the clonal profile of each sample passed in the list for that reason maybe you would get an out of memory having many samples.
> 
> 
> 
> Let me know if it is clear. Best Regards.
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 

Hi Antonio,

Thank you for sending the script! I will run it and get back to you.

**Comment by Niubile001** [comment]
> Hi Antonio,
> 
> It's running now, thank you!
> 
> Also, after getting all of my results, I would like to plot a single CN heatmap with all the samples and add an annotation bar for the individual cell types (cancer, and normal cells). How can I do this, and is there a vignette for this?
> 
> Best wishes, Constantinos

Dear Constantinos，

Could you please share the script for preparing the listNormCells[[x]]. I was able to build listCountMtx[[x]] but not familiar with the structure of listNormCells[[x]]. Any help would be appreciated! 

Best wishes,
Wang-Zhong Li

**Comment by AntonioDeFalco** [comment]
@Niubile001 @ConDem94,

if you reinstall SCEVAN I added the parameter listNormCells in the last commit https://github.com/AntonioDeFalco/SCEVAN/commit/285505291a538bbf93f743d8f7822e3812179858. Where you can pass normal cells as a list to be used as references added to the matrix.

as example : listNormCells <- list(NORM_CELL_COUNT_MTX1, NORM_CELL_COUNT_MTX2)
