### ISSUE TITLE
Error in step 11

### ISSUE THREAD

**Issue by 13021969200** [AntonioDeFalco/SCEVAN#72]
Dear SCEVAN developers,
I tried to perform SCEVAN on my own data, but I encountered this error below.
![2023-08-10 23-20-47屏幕截图](https://github.com/AntonioDeFalco/SCEVAN/assets/138771149/1e64e80c-86da-4033-9d13-5c4d97a3d50e)
![2023-08-10 23-21-29屏幕截图](https://github.com/AntonioDeFalco/SCEVAN/assets/138771149/3d621d90-8ab3-4e5b-89a9-bf9c3bd09c3f)
![2023-08-10 23-22-17屏幕截图](https://github.com/AntonioDeFalco/SCEVAN/assets/138771149/3b5405e4-a724-45f1-a357-452a68386147)
![2023-08-10 23-22-37屏幕截图](https://github.com/AntonioDeFalco/SCEVAN/assets/138771149/9a2b90da-5117-4039-98fc-7d18b3705b77)
I would appreciate it very much if you could offer me some suggestions. Thank you!

**Comment by AntonioDeFalco** [comment]
@13021969200 
As already suggested by e-mail, I recommend analysing the samples individually with SCEVAN with regard to the pipelineCNA function, and using the multiSampleComparisonClonalCN function instead if you want to compare several samples.

Let me know if this error also persists without aggregating the several matrices. Regards.

**Comment by whaly** [comment]
> Dear SCEVAN developers, I tried to perform SCEVAN on my own data, but I encountered this error below. ![2023-08-10 23-20-47屏幕截图](https://user-images.githubusercontent.com/138771149/259792751-1e64e80c-86da-4033-9d13-5c4d97a3d50e.png) ![2023-08-10 23-21-29屏幕截图](https://user-images.githubusercontent.com/138771149/259792876-3d621d90-8ab3-4e5b-89a9-bf9c3bd09c3f.png) ![2023-08-10 23-22-17屏幕截图](https://user-images.githubusercontent.com/138771149/259792945-3b5405e4-a724-45f1-a357-452a68386147.png) ![2023-08-10 23-22-37屏幕截图](https://user-images.githubusercontent.com/138771149/259793021-9a2b90da-5117-4039-98fc-7d18b3705b77.png) I would appreciate it very much if you could offer me some suggestions. Thank you!

hi, I met the same question as yours. Did you solve it? Would you mind share the solution? THX a lot!
