### ISSUE TITLE
Error in subclone analysis 

### ISSUE THREAD

**Issue by RaghadShu** [AntonioDeFalco/SCEVAN#73]
Hello, 
I am running multiple myeloma samples using pipelineCNA. 
For each run: I integrate a sample with normal public controls (using Seurat), I extract the raw matrix for SCEVAN, and also supply the names of the normal cells in the norm_cell condition. 
I do this because I want a normal reference against my tumor samples.

However, I get this error when I run: 

```
Error in `[<-.data.frame`(`*tmp*`, r, 1, value = c("2 (p22.3-p13.3) ",  : 
  replacement has 2 rows, data has 1
Calls: <Anonymous> ... subcloneAnalysisPipeline -> annoteBandOncoHeat -> [<- -> [<-.data.frame
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

Best,
Raghad

**Comment by whaly** [comment]
I met the same issue! Did you solve it? QAQ

**Comment by andynkili** [comment]
Same here!
I ran:
```
#mydata.list is a list of seurat objects
normal_cell<-subset(mydata, cells = WhichCells(mydata, expression = cancer.status=='normal'))
results.list <- lapply(names(mydata.list), function(x) {
        pipelineCNA(mydata.list[[x]]@assays$RNA@counts, sample = x, norm_cell = Cells(normal_cell.list[[x]]), SUBCLONES = TRUE, 
            ClonalCN = TRUE, par_cores = 8, plotTree=TRUE)
    })
```
And got the following error:
```
Error in `[<-.data.frame`(`*tmp*`, r, 1, value = c("13 (q12.11-q12.12) ",  : 
  replacement has 2 rows, data has 1
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Called from: `[<-.data.frame`(`*tmp*`, r, 1, value = c("13 (q12.11-q12.12) ", 
"13 (q12.11-q12.12) "))
```

**Comment by AntonioDeFalco** [comment]
Hello @whaly and @andynkili,
Try to reinstall SCEVAN and let me know if the bug is fixed after my last commit https://github.com/AntonioDeFalco/SCEVAN/commit/fcbecd5526f3f92184f2845b889df0b2c11db9c8.

Thanks. Regards

**Comment by andynkili** [comment]
@AntonioDeFalco,

Re-installing after your commit on the annoteBandOncoHeat function seems to fix the bug.

Thank you
