### ISSUE TITLE
How can I compare the copy number variation of two different types of tumour cells?

### ISSUE THREAD

**Issue by mbihie** [AntonioDeFalco/SCEVAN#76]
I want to compare the copy number variation of two different types of tumours using SCEVAN. I have two Seurat objects that correspond to each tumour type. They are multiple samples for each type integrated into two objects. 

1. I wanted to know if we can use a raw count matrix from a Seurat object that has multiple samples integrated. 

2. Would it be better to use the Seurat objects with all cell types present or filter it down to the known tumour cells?

Any guidance would be appreciated!

**Comment by AntonioDeFalco** [comment]
Hi @mbihie

> I wanted to know if we can use a raw count matrix from a Seurat object that has multiple samples integrated.

How were the multiple samples integrated? If the integrated matrix is not represented by embedding (low-dimensional representation) you can use it in SCEVAN (Although the use of SCEVAN on integrated matrix of different samples was not tested in our work).

> Would it be better to use the Seurat objects with all cell types present or filter it down to the known tumour cells?

You also need to have normal cells in the matrix to achieve copy number inference with SCEVAN, in case a reliable classification of normal cells is known it is recommended to pass it as _**norm_cells**_ parameter. 

Thanks for you interest. 

Regards

**Comment by mbihie** [comment]
Hi @AntonioDeFalco,

Thank you for the response!

The code used to generate the Seurat object ([object](https://figshare.com/articles/dataset/Data_R_code_and_output_Seurat_Objects_for_single_cell_RNA-seq_analysis_of_human_breast_tissues/17058077?file=31546385), [code](https://github.com/yunshun/HumanBreast10X/blob/main/RCode/TNBC.R)) did not use IntegrateEmbeddings() function so I believe it was not represented by embedding. 

For the normal cells, would I be able to extract the raw count matrix from both the tumor and normal objects and combine them using rbind? I want to compare two types of tumors, but I am not sure on how I can do so while also including the normal cells.

**Comment by AntonioDeFalco** [comment]
https://github.com/AntonioDeFalco/SCEVAN/issues/77
