### ISSUE TITLE
Inconsistence of copy number profile

### ISSUE THREAD

**Issue by wbf520qcp** [AntonioDeFalco/SCEVAN#79]
Hi 
I have run the tool on a group of samples harboring specific chromosome loss. However, the oncoheat and heatmap_subclones show the gain of that chromosome. Any hint on this?
Also, I wonder what is the difference between oncoheat and heatmap_subclones? Sometimes that seem to be inconsistent.
Thanks,

**Comment by AntonioDeFalco** [comment]
Hi @wbf520qcp,
Check that the normal cells are correctly identified, and if you can, share some pictures of the results here to help us understand the problem.

Thanks Regards.
