### ISSUE TITLE
exporting the results of OncoHeat for all chromosome position

### ISSUE THREAD

**Issue by moOsmanMD** [AntonioDeFalco/SCEVAN#80]
Thanks for developing such useful and robust tool.

I wonder if there is method to export that data used for the oncoheatmap but for all positions? 

Thanks.

**Comment by mbihie** [comment]
I Think it can be found in allPlotOncoHeat.RData from the output folder

**Comment by moOsmanMD** [comment]
this Rdata only have the source data for the plotted OncoHeat

**Comment by AntonioDeFalco** [comment]
hi @moOsmanMD,
If you are interested in the integer copy number for all positions, you will find this information in the .seg files.

Regards.
