### ISSUE TITLE
Raw counts in the instructions are inconsistent with examples? 

### ISSUE THREAD

**Issue by ahdee** [AntonioDeFalco/SCEVAN#84]
Hi, I'm looking through the vignette and it looks like both examples, 
http://htmlpreview.github.io/?https://github.com/AntonioDeFalco/SCEVAN/blob/main/vignettes/multiSamples.html 

uses log normalized counts as opposed to raw.  For example, here is subset of the example above. Notice that the numbers are in decimals as opposed to raw which should be in whole numbers?  So should we use  raw or normalized?  thanks a bunch.

```
> listCountMtx$MGH104[c(4:20), 2:5]
        MGH104-P5-A04 MGH104-P5-A05 MGH104-P5-A06 MGH104-P5-A07
A2M         0.0000000     0.0000000      6.256841    4.31404390
A2M-AS1     0.0000000     0.0000000      0.000000    0.58592398
A2ML1       0.1388145     0.0000000      0.230203    0.05519565
A2MP1       0.0000000     0.0000000      0.000000    0.00000000
A4GALT      0.0000000     0.0000000      0.000000    0.00000000
A4GNT       0.0000000     0.0000000      0.000000    0.00000000
AA06        0.0000000     0.0000000      0.000000    0.00000000
AAAS        2.4257278     3.7361719      1.678523    3.77715667
AACS        3.2360333     0.0000000      0.000000    0.00000000
```

**Comment by AntonioDeFalco** [comment]
Hi @ahdee,
It is preferable to start with RAW counts, unfortunately for those samples we have the matrix already log normalised.

Regards
