### ISSUE TITLE
What do the columns CN and segm.mean represent for the "CN.seg" file?

### ISSUE THREAD

**Issue by mbihie** [AntonioDeFalco/SCEVAN#85]
I was hoping to use the ```CN``` and ```segm.mean``` columns found in the ```subclone1_CN.seg``` files from the Intratumoral heterogeneity in Glioblastoma example. I wanted to use them to compare the copy number deletion of 1 type of cancer to another.  Could anyone clarify exactly what they mean? 

Thank you!

**Comment by AntonioDeFalco** [comment]
Hello @mbihie,
segm.mean is the mean CN log ratio of all cells of that subclone in a specific segment of the genome, and CN is the infer integer copy number obtained as explained in the our paper (4 amp 3 Gain 1 Loss 0 Del).

Regards
