### ISSUE TITLE
 'mc.cores' > 1 is not supported on Windows

### ISSUE THREAD

**Issue by xiangwei6963** [AntonioDeFalco/SCEVAN#9]
Hi Authors!!
I am trying to use this package. But it throws the following error:
Error in parallel::mclapply(1:ncol(count_mtx_relat), nonLinSmooth, mc.cores = par_cores) : 
  'mc.cores' > 1 is not supported on Windows
So I modified the code to "results <- SCEVAN::pipelineCNA(count_mtx,SUBCLONES = FALSE,par_cores=1)". 
Then, it works. However, it takes so long time to finish it. It has no progress for 2 hours.
Please help me understand how to deal with this?
Thank you!

**Comment by AntonioDeFalco** [comment]
Hi thanks for your interest in our tool, I'm sorry I was not aware of the incompatibility of mcapply with Windows. I have provided in the last commit [79a1ead](https://github.com/AntonioDeFalco/SCEVAN/commit/79a1eade40c91400409d3dab9e286448f507e0b6) to use parLapply in the case of Windows operating systems. Let me know if everything is ok now.

**Comment by xiangwei6963** [comment]
@AntonioDeFalco , thank you! I will have a try.

**Comment by AntonioDeFalco** [comment]
I have made some corrections to the code in the last few commits due to some compatibility issues on Windows. I also tested the tool on windows and now it works correctly in parallel.

```
sessionInfo()
R version 4.1.2 (2021-11-01)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)
```
