### ISSUE TITLE
Error in names(segmList)

### ISSUE THREAD

**Issue by asl58** [AntonioDeFalco/SCEVAN#94]
I have a problem processing one of the samples.

This is the error message:

Error in names(segmList) <- paste0("subclone", 1:nSub) : 
  'names' attribute [10] must be the same length as the vector [9]
Calls: pipelineCNA -> subcloneAnalysisPipeline -> plotConsensusCNA

Thank you

**Comment by augjensen** [comment]
I had the same error. It seems like the entire pipeline only works for datasets generating less than 10 subclones. Is there a way to fix this problem?
