### ISSUE TITLE
control over cell/gene filtering

### ISSUE THREAD

**Issue by andynkili** [AntonioDeFalco/SCEVAN#98]
@AntonioDeFalco ,

Thank you for your helpful and user-friendly tool.
The current approach for cells and genes filtering ("cells with less than 200 detected genes and the genes expressed in less than 1% of cells are removed") might be too 'general' especially for genes differentially expressed in small clusters: in our case, some of our datasets include very small quiescent cell type population (~ 100 cells not expressing many genes, but the latter are differentially expressed).
In that particular case, removing genes not expressed in at least 1% of the whole dataset and cells not expressing at least 200 genes may lead to missing relevant CNVs.
Would it be possible to turn off filtering or better: give more control over the parameter threshold so we can manually draw the line between noise and actual CNVs?

Best,
Andy

**Comment by AntonioDeFalco** [comment]
Hi @andynkili,
If you install the last version of SCEVAN in the pipelineCNA function, you can now use the parameter _**perc_genes**_ and use your percentage. However, I think it is impossible to analyze cells with less than 200 genes; I consider them to be of too low quality and unusable for copy number analysis. But if you want to try, you can modify the **_preprocessingMtx_** function in the GitHub.

Thanks. Regards
