### ISSUE TITLE
Restrictions on input files

### ISSUE THREAD

**Issue by Moey-git** [AntonioDeFalco/SCEVAN#99]
Hello Antonio,
Thank you for SCEVAN which works fine for me, however, I have a question on the input file.I want to know if the column of the input matrix has a minimum number of cells.Because when I have only 160+ cells, I get the following error
`Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], Subclones = pred) :
Parameter values mean different number of rows : 0, 38`
And I've seen people work around the bug by increasing the cell count.So I'm trying to determine if there is such a thing as a minimum limit on the number of cells.
Thank you for your help.

**Comment by AntonioDeFalco** [comment]
Hi @Moey-git 

There is probably some problem in the analysis of subclones with such a small number of cells. If you are not interested in subclone analysis you can set  SUBCLONES = FALSE.

Thanks. Regards.

**Comment by Moey-git** [comment]
Thank you @AntonioDeFalco!
